services:
  celery_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=celery_worker
    command: celery -A core worker --autoscale=5,1 --hostname=celery_worker@%h
    restart: always

  worker_traders_reboot:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=worker_traders_reboot
    command: celery -A core worker -Q traders_reboot --autoscale=1,1 --hostname=worker_traders_reboot@%h
    restart: always

  worker_optimizers_optimize:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=worker_optimizers_optimize
    command: celery -A core worker -Q optimizers_optimize --autoscale=1,1 --hostname=worker_optimizers_optimize@%h
    restart: always

  candle_source_rest_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=candle_source_rest_worker
    command: celery -A core worker -Q candle_sources_rest --concurrency=1 --hostname=candle_source_rest_worker@%h
    restart: always

  exchange_client_rpc_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=exchange_client_rpc_worker
    command: python manage.py run_exchange_client_rpc_worker
    restart: always

  trader_ws_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=trader_ws_worker
    command: python manage.py run_trader_ws_worker
    restart: always

  candle_source_ws_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=candle_source_ws_worker
    command: python manage.py run_candle_source_ws_worker
    restart: always
