services:
  celery_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=celery_worker
    command: celery -A core worker --autoscale=5,1 --hostname=celery_worker
    restart: always

  trader_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=trader_worker
    command: celery -A core worker -Q trader --autoscale=1,1 --hostname=trader_worker
    restart: always

  optimizer_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=optimizer_worker
    command: celery -A core worker -Q optimizer --autoscale=1,1 --hostname=optimizer_worker
    restart: always

  candle_source_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=candle_source_worker
    command: celery -A core worker -Q candle_source --autoscale=1,1 --hostname=candle_source_worker
    restart: always

  exchange_client_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=exchange_client_worker
    command: celery -A core worker -Q exchange_client --autoscale=1,1 --hostname=exchange_client_worker
    restart: always

  exchange_client_rpc_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=exchange_client_rpc_worker
    command: python manage.py run_exchange_client_rpc_worker
    restart: always

  trader_ws_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=trader_ws_worker
    command: python manage.py run_trader_ws_worker
    restart: always

  candle_source_ws_worker:
    image: kletkinvasilii/trader:staging
    env_file:
      - ./.env
    environment:
      - POSTGRES_APP_NAME=candle_source_ws_worker
    command: python manage.py run_candle_source_ws_worker
    restart: always
