# Generated by Django 5.2.6 on 2025-12-24 20:19

import candle_providers.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandleProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('class_name', models.CharField(choices=candle_providers.domain.base.CandleProviderRegistry.get_choices, max_length=100, verbose_name='Класс провайдера свечей')),
            ],
            options={
                'verbose_name': 'Candle Provider',
                'verbose_name_plural': 'Candle Providers',
            },
        ),
    ]
