# Generated by Django 5.2.6 on 2025-12-24 15:29

import candle_providers.domain.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candle_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('class_name', models.CharField(choices=candle_providers.domain.base.CandleProviderRegistry.get_choices, help_text='Тип провайдера (ExchangeCandleProvider, ArbitrageCandleProvider и т.д.)', max_length=100, verbose_name='Класс провайдера свечей')),
                ('primary_source', models.ForeignKey(help_text='Основной источник свечей (обязательный для всех типов провайдеров)', on_delete=django.db.models.deletion.CASCADE, related_name='primary_candle_providers', to='candle_sources.candlesource', verbose_name='Первичный источник свечей')),
                ('secondary_source', models.ForeignKey(blank=True, help_text='Дополнительный источник (только для ArbitrageCandleProvider)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_candle_providers', to='candle_sources.candlesource', verbose_name='Вторичный источник свечей')),
            ],
            options={
                'verbose_name': 'Candle Provider',
                'verbose_name_plural': 'Candle Providers',
            },
        ),
    ]
