# Generated by Django 5.2.6 on 2025-12-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candle_providers', '0001_initial'),
        ('candle_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candleprovider',
            name='primary_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_candle_providers', to='candle_sources.candlesource', verbose_name='Первичный источник свечей'),
        ),
        migrations.AddField(
            model_name='candleprovider',
            name='secondary_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_candle_providers', to='candle_sources.candlesource', verbose_name='Вторичный источник свечей'),
        ),
    ]
