services:
  postgres:
    image: postgres:14.18-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    env_file:
      - ./.env

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - postgres
      - redis
    entrypoint: bash entrypoint.sh
    command: debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A backend flower
    volumes:
      - .:/app
    ports:
      - 5555:5555
    depends_on:
      - postgres
      - redis
      - backend

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
      - backend
    command: celery -A core beat -l info

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
      - backend
    command: celery -A core worker -l info
