# Generated by Django 5.2.6 on 2025-12-08 14:23

import django.core.validators
import django.db.models.deletion
import optimizers.domain.base
import risk_managers.domain.base
import strategies.domain.base
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_clients', '0001_initial'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderOptimizationAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название алгоритма оптимизации')),
                ('class_name', models.CharField(choices=optimizers.domain.base.OptimizerRegistry.get_choices, max_length=100, verbose_name='Класс стратегии')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)')),
            ],
            options={
                'verbose_name': 'Алгоритм оптимизации',
                'verbose_name_plural': 'Алгоритмы оптимизации',
            },
        ),
        migrations.CreateModel(
            name='TraderOptimizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('error', 'Error')], default='enabled', help_text='Текущий статус оптимизатора трейдера.', max_length=10, verbose_name='Статус оптимизатора')),
                ('strategy_class_name', models.CharField(choices=strategies.domain.base.StrategyRegistry.get_choices, max_length=100, verbose_name='Класс стратегии')),
                ('risk_manager_class_name', models.CharField(choices=risk_managers.domain.base.RiskManagerRegistry.get_choices, max_length=100, verbose_name='Класс риск-менеджера')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Начальный баланс')),
                ('max_positions_count', models.PositiveSmallIntegerField(default=1, help_text='Максимальное количество одновременно открытых позиций.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Макс. количество позиций')),
                ('close_position_by_opposite_signal', models.BooleanField(default=True, help_text='Если выбрано, будет закрывать позицию при получении противоположного сигнала.', verbose_name='Закрывать позиции при противоположном сигнале')),
                ('close_position_by_strategy', models.BooleanField(default=True, help_text='Если выбрано, будет закрывать позицию при получении сигнала от стратегии.', verbose_name='Закрывать позиции по сигналу стратегии')),
                ('close_position_by_stop_loss', models.BooleanField(default=True, help_text='Если выбрано, будет закрывать позицию при достижении Stop Loss.', verbose_name='Закрывать позиции по Stop Loss')),
                ('close_position_by_take_profit', models.BooleanField(default=True, help_text='Если выбрано, будет закрывать позицию при достижении Take Profit.', verbose_name='Закрывать позиции по Take Profit')),
                ('trail_stop_enabled', models.BooleanField(default=True, help_text='Если выбрано, будет использовать трейлинг-стоп для позиций.', verbose_name='Трейлинг-стоп')),
                ('algorithm', models.ForeignKey(help_text='Выберите алгоритм оптимизации для данного оптимизатора.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='optimizers.traderoptimizationalgorithm', verbose_name='Алгоритм оптимизации')),
                ('candle_source', models.ForeignKey(help_text='Выберите источник свечей для данного оптимизатора.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclientcandlesource', verbose_name='Источник свечей')),
                ('exchange', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа')),
            ],
            options={
                'verbose_name': 'Оптимизатор трейдера',
                'verbose_name_plural': 'Оптимизаторы трейдеров',
            },
        ),
        migrations.CreateModel(
            name='TraderOptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('theoretical_profit', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Теоретическая прибыль')),
                ('strategy_arguments', models.JSONField()),
                ('risk_manager_arguments', models.JSONField()),
                ('errors', models.TextField(blank=True, help_text='Лог ошибок, возникших во время оптимизации.', verbose_name='Ошибки')),
                ('optimizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizers.traderoptimizer', verbose_name='Конфигурация оптимизации')),
            ],
            options={
                'verbose_name': 'Результат оптимизации',
                'verbose_name_plural': 'Результаты оптимизации',
            },
        ),
        migrations.AddConstraint(
            model_name='traderoptimizer',
            constraint=models.UniqueConstraint(fields=('algorithm', 'exchange', 'candle_source', 'strategy_class_name', 'risk_manager_class_name', 'initial_balance', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled'), name='unique_trader_optimizer'),
        ),
    ]
