# Generated by Django 5.2.6 on 2025-11-18 21:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0005_tradingpair_fee_percent_tradingpair_max_amount_and_more'),
        ('risk_managers', '0004_alter_riskmanager_name'),
        ('strategies', '0004_alter_strategy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optimizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('RUNNING', 'Выполняется'), ('COMPLETED', 'Завершен'), ('FAILED', 'Ошибка')], default='PENDING', help_text='Текущий статус оптимизатора трейдера.', max_length=10, verbose_name='Статус оптимизатора')),
                ('favorite', models.BooleanField(default=False, help_text='Отметьте, если хотите добавить трейдера в избранное.', verbose_name='Избранный оптимизатор')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', help_text='Выберите таймфрейм, на котором будет работать трейдер.', max_length=10, verbose_name='Таймфрейм')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Начальный баланс')),
                ('max_drawdown_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Максимальная допустимая просадка в процентах от начального баланса.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Макс. просадка (%)')),
                ('max_positions_count', models.PositiveSmallIntegerField(default=1, help_text='Максимальное количество одновременно открытых позиций.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Макс. количество позиций')),
                ('close_position_by_opposite_signal', models.BooleanField(default=True, help_text='Если выбрано, будет закрывать позицию при получении противоположного сигнала.', verbose_name='Закрывать позиции при противоположном сигнале')),
                ('close_position_by_strategy', models.BooleanField(default=True, help_text='Если выбрано, будет закрывать позицию при получении сигнала от стратегии.', verbose_name='Закрывать позиции по сигналу стратегии')),
                ('close_position_by_stop_loss', models.BooleanField(default=True, help_text='Если выбрано, будет закрывать позицию при достижении Stop Loss.', verbose_name='Закрывать позиции по Stop Loss')),
                ('close_position_by_take_profit', models.BooleanField(default=True, help_text='Если выбрано, будет закрывать позицию при достижении Take Profit.', verbose_name='Закрывать позиции по Take Profit')),
                ('trail_stop_enabled', models.BooleanField(default=True, help_text='Если выбрано, будет использовать трейлинг-стоп для позиций.', verbose_name='Трейлинг-стоп')),
                ('last_reboot', models.DateTimeField(blank=True, help_text='Дата и время последнего перезапуска трейдера.', null=True, verbose_name='Последний перезапуск')),
                ('errors', models.TextField(blank=True, null=True)),
                ('last_error', models.DateTimeField(blank=True, help_text='Дата и время последней ошибки трейдера. ', null=True, verbose_name='Последняя ошибка')),
                ('exchange', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа')),
                ('risk_manager', models.ForeignKey(help_text='Выберите риск-менеджер, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='risk_managers.riskmanager', verbose_name='Риск-менеджер')),
                ('strategy', models.ForeignKey(help_text='Выберите стратегию, которую будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy', verbose_name='Стратегия')),
                ('trading_pair', models.ForeignKey(help_text='Укажите торговую пару, с которой будет работать трейдер.', on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Оптимизатор',
                'verbose_name_plural': 'Оптимизаторы',
            },
        ),
        migrations.CreateModel(
            name='OptimizerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('theoretical_profit', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Теоретическая прибыль')),
                ('strategy_arguments', models.JSONField()),
                ('optimizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizers.optimizer')),
            ],
            options={
                'verbose_name': 'Отчет оптимизации',
                'verbose_name_plural': 'Отчеты оптимизации',
            },
        ),
    ]
