# Generated by Django 5.2.6 on 2025-12-09 00:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0001_initial'),
        ('exchanges', '0001_initial'),
        ('optimizers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderoptimizer',
            name='unique_trader_optimizer',
        ),
        migrations.RenameField(
            model_name='traderoptimizationresult',
            old_name='theoretical_profit',
            new_name='pnl',
        ),
        migrations.RemoveField(
            model_name='traderoptimizer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='avg_candles_per_position',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Среднее время удержания позиции в свечах.', max_digits=10, verbose_name='Среднее количество свечей на позицию'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='avg_pnl_per_position',
            field=models.DecimalField(decimal_places=10, default=1, help_text='Средняя прибыль/убыток на одну позицию.', max_digits=20, verbose_name='Средний PnL на позицию'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='pnl_r2',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Коэффициент детерминации для накопленного PnL (0.0 - 1.0).', max_digits=5, verbose_name='R² для PnL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='roi',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Return on Investment (прибыль / начальный баланс).', max_digits=10, verbose_name='ROI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='sharpe',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Коэффициент Шарпа (риск-скорректированная доходность).', max_digits=10, verbose_name='Sharpe Ratio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='total_positions',
            field=models.PositiveIntegerField(default=1, help_text='Количество открытых позиций во время симуляции.', verbose_name='Общее количество позиций'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='win_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Доля прибыльных сделок (0.0 - 1.0).', max_digits=5, verbose_name='Процент прибыльных сделок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderoptimizer',
            name='r2_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Вес R² в комбинированной оценке (0.00 - 1.00).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Вес R²'),
        ),
        migrations.AddField(
            model_name='traderoptimizer',
            name='roi_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.40'), help_text='Вес ROI в комбинированной оценке (0.00 - 1.00).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Вес ROI'),
        ),
        migrations.AddField(
            model_name='traderoptimizer',
            name='sharpe_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Вес Sharpe в комбинированной оценке (0.00 - 1.00).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Вес Sharpe'),
        ),
        migrations.AddField(
            model_name='traderoptimizer',
            name='win_rate_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Вес Win Rate в комбинированной оценке (0.00 - 1.00).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Вес Win Rate'),
        ),
        migrations.AlterField(
            model_name='traderoptimizationresult',
            name='risk_manager_arguments',
            field=models.JSONField(help_text='Оптимальные параметры риск-менеджера.', verbose_name='Параметры риск-менеджера'),
        ),
        migrations.AlterField(
            model_name='traderoptimizationresult',
            name='strategy_arguments',
            field=models.JSONField(help_text='Оптимальные параметры стратегии.', verbose_name='Параметры стратегии'),
        ),
        migrations.AddConstraint(
            model_name='traderoptimizer',
            constraint=models.UniqueConstraint(fields=('algorithm', 'exchange', 'candle_source', 'strategy_class_name', 'risk_manager_class_name', 'initial_balance', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled', 'roi_weight', 'r2_weight', 'sharpe_weight', 'win_rate_weight'), name='unique_trader_optimizer'),
        ),
    ]
