# Generated by Django 5.2.6 on 2025-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizer',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('error', 'Error')], default='enabled', help_text='Текущий статус оптимизатора трейдера.', max_length=10, verbose_name='Статус оптимизатора'),
        ),
    ]
