# Generated by Django 5.2.6 on 2025-11-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0002_alter_optimizer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimizerresult',
            options={'verbose_name': 'Результат оптимизации', 'verbose_name_plural': 'Результаты оптимизации'},
        ),
    ]
