# Generated by Django 5.2.6 on 2025-12-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0002_remove_traderoptimizer_unique_trader_optimizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='duration',
            field=models.DurationField(default='365 days, 0:00:00', help_text='Время, затраченное на выполнение оптимизации.', verbose_name='Длительность оптимизации'),
            preserve_default=False,
        ),
    ]
