# Generated by Django 5.2.6 on 2025-12-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0003_traderoptimizationresult_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderoptimizationresult',
            name='avg_pnl_per_position',
        ),
    ]
