# Generated by Django 5.2.6 on 2025-11-30 12:48

import django.db.models.deletion
import optimizers.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_tradingpair_fee_percent_tradingpair_max_amount_and_more'),
        ('optimizers', '0004_optimizer_unique_optimizer'),
        ('risk_managers', '0004_alter_riskmanager_name'),
        ('strategies', '0004_alter_strategy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название алгоритма оптимизации')),
                ('class_name', models.CharField(choices=optimizers.domain.base.OptimizerRegistry.get_choices, max_length=100, verbose_name='Класс стратегии')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)')),
            ],
            options={
                'verbose_name': 'Алгоритм оптимизации',
                'verbose_name_plural': 'Алгоритмы оптимизации',
            },
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('theoretical_profit', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Теоретическая прибыль')),
                ('strategy_arguments', models.JSONField()),
                ('errors', models.TextField(blank=True, help_text='Лог ошибок, возникших во время оптимизации.', verbose_name='Ошибки')),
            ],
            options={
                'verbose_name': 'Результат оптимизации',
                'verbose_name_plural': 'Результаты оптимизации',
            },
        ),
        migrations.RemoveField(
            model_name='optimizerresult',
            name='optimizer',
        ),
        migrations.AlterModelOptions(
            name='optimizer',
            options={'verbose_name': 'Оптимизатор трейдера', 'verbose_name_plural': 'Оптимизаторы трейдеров'},
        ),
        migrations.RemoveConstraint(
            model_name='optimizer',
            name='unique_optimizer',
        ),
        migrations.RemoveField(
            model_name='optimizer',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='optimizer',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='optimizer',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='optimizer',
            name='last_reboot',
        ),
        migrations.AlterField(
            model_name='optimizer',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1h', help_text='Выберите таймфрейм, на котором будет работать трейдер.', max_length=10, verbose_name='Таймфрейм'),
        ),
        migrations.AddConstraint(
            model_name='optimizer',
            constraint=models.UniqueConstraint(fields=('exchange', 'trading_pair', 'timeframe', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled'), name='unique_trader_optimizer'),
        ),
        migrations.AddField(
            model_name='optimizationresult',
            name='optimizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizers.optimizer', verbose_name='Конфигурация оптимизации'),
        ),
        migrations.DeleteModel(
            name='OptimizerResult',
        ),
    ]
