# Generated by Django 5.2.6 on 2025-12-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0002_candlesource_is_active'),
        ('optimizers', '0004_remove_traderoptimizationresult_avg_pnl_per_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderoptimizer',
            name='candle_source',
            field=models.ForeignKey(help_text='Выберите источник свечей для данного оптимизатора.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='candle_sources.candlesource', verbose_name='Источник свечей'),
        ),
    ]
