# Generated by Django 5.2.6 on 2025-11-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0005_optimizationalgorithm_optimizationresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizer',
            name='algorithm',
            field=models.ForeignKey(default=1, help_text='Выберите алгоритм оптимизации для данного оптимизатора.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='optimizers.optimizationalgorithm', verbose_name='Алгоритм оптимизации'),
            preserve_default=False,
        ),
    ]
