# Generated by Django 5.2.6 on 2025-11-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_tradingpair_fee_percent_tradingpair_max_amount_and_more'),
        ('optimizers', '0006_optimizer_algorithm'),
        ('risk_managers', '0004_alter_riskmanager_name'),
        ('strategies', '0004_alter_strategy_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='optimizer',
            name='unique_trader_optimizer',
        ),
        migrations.AddConstraint(
            model_name='optimizer',
            constraint=models.UniqueConstraint(fields=('algorithm', 'exchange', 'trading_pair', 'timeframe', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled'), name='unique_trader_optimizer'),
        ),
    ]
