# Generated by Django 5.2.6 on 2025-12-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_tradingpair_fee_percent_tradingpair_max_amount_and_more'),
        ('optimizers', '0007_remove_optimizer_unique_trader_optimizer_and_more'),
        ('risk_managers', '0004_alter_riskmanager_name'),
        ('strategies', '0004_alter_strategy_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptimizationAlgorithm',
            new_name='TraderOptimizationAlgorithm',
        ),
        migrations.RenameModel(
            old_name='OptimizationResult',
            new_name='TraderOptimizationResult',
        ),
        migrations.RenameModel(
            old_name='Optimizer',
            new_name='TraderOptimizer',
        ),
    ]
