# Generated by Django 5.2.6 on 2025-12-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0008_rename_optimizationalgorithm_traderoptimizationalgorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderoptimizationresult',
            name='risk_manager_arguments',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
