# Generated by Django 5.2.6 on 2025-12-02 18:10

import risk_managers.domain.base
import strategies.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0009_traderoptimizationresult_risk_manager_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderoptimizer',
            name='risk_manager_class_name',
            field=models.CharField(choices=risk_managers.domain.base.RiskManagerRegistry.get_choices, default='ExtremumTPRRByRiskManager', max_length=100, verbose_name='Класс риск-менеджера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderoptimizer',
            name='strategy_class_name',
            field=models.CharField(choices=strategies.domain.base.StrategyRegistry.get_choices, default='StochasticStrategy', max_length=100, verbose_name='Класс стратегии'),
            preserve_default=False,
        ),
    ]
