# Generated by Django 5.2.6 on 2025-12-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0010_traderoptimizer_risk_manager_class_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderoptimizer',
            name='unique_trader_optimizer',
        ),
    ]
