# Generated by Django 5.2.6 on 2025-12-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_tradingpair_fee_percent_tradingpair_max_amount_and_more'),
        ('optimizers', '0011_remove_traderoptimizer_unique_trader_optimizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderoptimizer',
            name='risk_manager',
        ),
        migrations.RemoveField(
            model_name='traderoptimizer',
            name='strategy',
        ),
        migrations.AddConstraint(
            model_name='traderoptimizer',
            constraint=models.UniqueConstraint(fields=('algorithm', 'exchange', 'trading_pair', 'timeframe', 'strategy_class_name', 'risk_manager_class_name', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled'), name='unique_trader_optimizer'),
        ),
    ]
