# Generated by Django 5.2.6 on 2025-12-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0012_remove_traderoptimizer_risk_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderoptimizer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
