# Generated by Django 5.2.6 on 2025-12-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_tradingpair_fee_percent_tradingpair_max_amount_and_more'),
        ('optimizers', '0013_traderoptimizer_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderoptimizer',
            name='unique_trader_optimizer',
        ),
        migrations.AddConstraint(
            model_name='traderoptimizer',
            constraint=models.UniqueConstraint(fields=('algorithm', 'exchange', 'trading_pair', 'timeframe', 'strategy_class_name', 'risk_manager_class_name', 'initial_balance', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled'), name='unique_trader_optimizer'),
        ),
    ]
