# Generated by Django 5.2.6 on 2025-12-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizers', '0014_remove_traderoptimizer_unique_trader_optimizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderoptimizer',
            name='max_drawdown_pct',
        ),
    ]
