# Generated by Django 5.2.6 on 2026-02-14 21:23

import django.db.models.deletion
import exchange_clients.domain.base
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('class_name', models.CharField(choices=exchange_clients.domain.base.ExchangeClientRegistry.get_choices, max_length=30, unique=True, verbose_name='Класс клиента')),
                ('candle_fetch_limit', models.PositiveIntegerField(default=999, verbose_name='Лимит загрузки свечей')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(default='BTC/USDT', max_length=50, unique=True, verbose_name='Название')),
                ('symbol', models.CharField(default='BTC/USDT:USDT', max_length=50, unique=True, verbose_name='Символ')),
                ('min_amount', models.DecimalField(decimal_places=18, default=Decimal('0.001'), max_digits=30, verbose_name='Минимальное количество')),
                ('max_amount', models.DecimalField(decimal_places=18, default=Decimal('1000000'), max_digits=30, verbose_name='Максимальное количество')),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.1'), max_digits=5, verbose_name='Комиссия (%)')),
            ],
            options={
                'verbose_name': 'Торговая пара',
                'verbose_name_plural': 'Торговые пары',
            },
        ),
        migrations.CreateModel(
            name='ExchangeTradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('symbol', models.CharField(default='BTC/USDT:USDT', max_length=50, unique=True, verbose_name='Символ')),
                ('min_amount', models.DecimalField(decimal_places=18, default=Decimal('0.001'), max_digits=30, verbose_name='Минимальное количество')),
                ('max_amount', models.DecimalField(decimal_places=18, default=Decimal('1000000'), max_digits=30, verbose_name='Максимальное количество')),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.1'), max_digits=5, verbose_name='Комиссия (%)')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Торговая пара биржи',
                'verbose_name_plural': 'Торговые пары бирж',
                'constraints': [models.UniqueConstraint(fields=('exchange', 'trading_pair'), name='unique_exchange_trading_pair')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Максимальная цена')),
                ('low', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Минимальная цена')),
                ('open', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена открытия')),
                ('close', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена закрытия')),
                ('volume', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Объём торгов')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], max_length=3, verbose_name='Таймфрейм')),
                ('timestamp', models.DateTimeField(verbose_name='Временная метка')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Свеча биржи',
                'verbose_name_plural': 'Свечи бирж',
                'constraints': [models.UniqueConstraint(fields=('exchange', 'timeframe', 'trading_pair', 'timestamp'), name='unique_candle')],
            },
        ),
    ]
