# Generated by Django 5.2.1 on 2025-06-28 19:28

import django.db.models.deletion
import exchanges.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('class_name', models.CharField(choices=exchanges.domain.base.ExchangeClientRegistry.get_choices, max_length=30)),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(max_length=200)),
                ('demo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Клиент Биржи',
                'verbose_name_plural': 'Клиенты Бирж',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('socks5', 'Socks5'), ('socks4', 'Socks4')], default='socks5', max_length=10)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_pair', models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('ADA/USDT', 'ADA/USDT'), ('XRP/USDT', 'XRP/USDT'), ('KAS/USDT', 'KAS/USDT'), ('DEEP/USDT', 'DEEP/USDT'), ('DOGE/USDT', 'DOGE/USDT'), ('LINK/USDT', 'LINK/USDT'), ('SHIB1000/USDT', 'SHIB1000/USDT'), ('AVAX/USDT', 'AVAX/USDT'), ('MLN/USDT', 'MLN/USDT'), ('DOT/USDT', 'DOT/USDT'), ('BIO/USDT', 'BIO/USDT'), ('CLOUD/USDT', 'CLOUD/USDT'), ('CORE/USDT', 'CORE/USDT'), ('RONIN/USDT', 'RONIN/USDT'), ('SHELLU/SDT', 'SHELLU/SDT'), ('SOLAYER/USDT', 'SOLAYER/USDT'), ('VIRTUAL/USDT', 'VIRTUAL/USDT'), ('ARB/USDT', 'ARB/USDT'), ('BSV/USDT', 'BSV/USDT'), ('DOGS/USDT', 'DOGS/USDT'), ('GMT/USDT', 'GMT/USDT'), ('NTRN/USDT', 'NTRN/USDT'), ('COTI/USDT', 'COTI/USDT'), ('KOMA/USDT', 'KOMA/USDT'), ('BMT/USDT', 'BMT/USDT'), ('THE/USDT', 'THE/USDT'), ('GODS/USDT', 'GODS/USDT'), ('ZRO/USDT', 'ZRO/USDT'), ('CAKE/USDT', 'CAKE/USDT'), ('TRX/USDT', 'TRX/USDT'), ('PARTI/USDT', 'PARTI/USDT'), ('XTER/USDT', 'XTER/USDT'), ('SYN/USDT', 'SYN/USDT'), ('ACX/USDT', 'ACX/USDT'), ('MAVIA/USDT', 'MAVIA/USDT'), ('XCN/USDT', 'XCN/USDT'), ('CETUS/USDT', 'CETUS/USDT'), ('AIXBT/USDT', 'AIXBT/USDT'), ('SUI/USDT', 'SUI/USDT'), ('XRD/USDT', 'XRD/USDT'), ('PROMPT/USDT', 'PROMPT/USDT'), ('SPELL/USDT', 'SPELL/USDT'), ('PNUT/USDT', 'PNUT/USDT'), ('AR/USDT', 'AR/USDT'), ('MICHI/USDT', 'MICHI/USDT'), ('MERL/USDT', 'MERL/USDT'), ('AVAIL/USDT', 'AVAIL/USDT'), ('AI/USDT', 'AI/USDT'), ('UNI/USDT', 'UNI/USDT'), ('IP/USDT', 'IP/USDT'), ('ZEN/USDT', 'ZEN/USDT'), ('AEVO/USDT', 'AEVO/USDT'), ('AI16Z/USDT', 'AI16Z/USDT'), ('LOOKS/USDT', 'LOOKS/USDT'), ('XVG/USDT', 'XVG/USDT'), ('SLERF/USDT', 'SLERF/USDT'), ('GMX/USDT', 'GMX/USDT'), ('RENDER/USDT', 'RENDER/USDT'), ('TNSR/USDT', 'TNSR/USDT'), ('GALA/USDT', 'GALA/USDT'), ('IO/USDT', 'IO/USDT'), ('RPL/USDT', 'RPL/USDT'), ('SWEAT/USDT', 'SWEAT/USDT'), ('TIA/USDT', 'TIA/USDT'), ('BLAST/USDT', 'BLAST/USDT'), ('CPOOL/USDT', 'CPOOL/USDT'), ('ONT/USDT', 'ONT/USDT'), ('ETC/USDT', 'ETC/USDT'), ('SUN/USDT', 'SUN/USDT'), ('DGB/USDT', 'DGB/USDT'), ('PORTAL/USDT', 'PORTAL/USDT'), ('STG/USDT', 'STG/USDT'), ('PIXEL/USDT', 'PIXEL/USDT'), ('S/USDT', 'S/USDT'), ('RIF/USDT', 'RIF/USDT'), ('WAXP/USDT', 'WAXP/USDT'), ('NS/USDT', 'NS/USDT'), ('OSMO/USDT', 'OSMO/USDT'), ('MOBILE/USDT', 'MOBILE/USDT'), ('ANKR/USDT', 'ANKR/USDT'), ('ALICE/USDT', 'ALICE/USDT')], max_length=20)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3)),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangeclient')),
            ],
            options={
                'verbose_name': 'Источник свечей',
                'verbose_name_plural': 'Источники свечей',
            },
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_order_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='opened', max_length=10)),
                ('type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], default='market', max_length=10)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('trading_pair', models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('ADA/USDT', 'ADA/USDT'), ('XRP/USDT', 'XRP/USDT'), ('KAS/USDT', 'KAS/USDT'), ('DEEP/USDT', 'DEEP/USDT'), ('DOGE/USDT', 'DOGE/USDT'), ('LINK/USDT', 'LINK/USDT'), ('SHIB1000/USDT', 'SHIB1000/USDT'), ('AVAX/USDT', 'AVAX/USDT'), ('MLN/USDT', 'MLN/USDT'), ('DOT/USDT', 'DOT/USDT'), ('BIO/USDT', 'BIO/USDT'), ('CLOUD/USDT', 'CLOUD/USDT'), ('CORE/USDT', 'CORE/USDT'), ('RONIN/USDT', 'RONIN/USDT'), ('SHELLU/SDT', 'SHELLU/SDT'), ('SOLAYER/USDT', 'SOLAYER/USDT'), ('VIRTUAL/USDT', 'VIRTUAL/USDT'), ('ARB/USDT', 'ARB/USDT'), ('BSV/USDT', 'BSV/USDT'), ('DOGS/USDT', 'DOGS/USDT'), ('GMT/USDT', 'GMT/USDT'), ('NTRN/USDT', 'NTRN/USDT'), ('COTI/USDT', 'COTI/USDT'), ('KOMA/USDT', 'KOMA/USDT'), ('BMT/USDT', 'BMT/USDT'), ('THE/USDT', 'THE/USDT'), ('GODS/USDT', 'GODS/USDT'), ('ZRO/USDT', 'ZRO/USDT'), ('CAKE/USDT', 'CAKE/USDT'), ('TRX/USDT', 'TRX/USDT'), ('PARTI/USDT', 'PARTI/USDT'), ('XTER/USDT', 'XTER/USDT'), ('SYN/USDT', 'SYN/USDT'), ('ACX/USDT', 'ACX/USDT'), ('MAVIA/USDT', 'MAVIA/USDT'), ('XCN/USDT', 'XCN/USDT'), ('CETUS/USDT', 'CETUS/USDT'), ('AIXBT/USDT', 'AIXBT/USDT'), ('SUI/USDT', 'SUI/USDT'), ('XRD/USDT', 'XRD/USDT'), ('PROMPT/USDT', 'PROMPT/USDT'), ('SPELL/USDT', 'SPELL/USDT'), ('PNUT/USDT', 'PNUT/USDT'), ('AR/USDT', 'AR/USDT'), ('MICHI/USDT', 'MICHI/USDT'), ('MERL/USDT', 'MERL/USDT'), ('AVAIL/USDT', 'AVAIL/USDT'), ('AI/USDT', 'AI/USDT'), ('UNI/USDT', 'UNI/USDT'), ('IP/USDT', 'IP/USDT'), ('ZEN/USDT', 'ZEN/USDT'), ('AEVO/USDT', 'AEVO/USDT'), ('AI16Z/USDT', 'AI16Z/USDT'), ('LOOKS/USDT', 'LOOKS/USDT'), ('XVG/USDT', 'XVG/USDT'), ('SLERF/USDT', 'SLERF/USDT'), ('GMX/USDT', 'GMX/USDT'), ('RENDER/USDT', 'RENDER/USDT'), ('TNSR/USDT', 'TNSR/USDT'), ('GALA/USDT', 'GALA/USDT'), ('IO/USDT', 'IO/USDT'), ('RPL/USDT', 'RPL/USDT'), ('SWEAT/USDT', 'SWEAT/USDT'), ('TIA/USDT', 'TIA/USDT'), ('BLAST/USDT', 'BLAST/USDT'), ('CPOOL/USDT', 'CPOOL/USDT'), ('ONT/USDT', 'ONT/USDT'), ('ETC/USDT', 'ETC/USDT'), ('SUN/USDT', 'SUN/USDT'), ('DGB/USDT', 'DGB/USDT'), ('PORTAL/USDT', 'PORTAL/USDT'), ('STG/USDT', 'STG/USDT'), ('PIXEL/USDT', 'PIXEL/USDT'), ('S/USDT', 'S/USDT'), ('RIF/USDT', 'RIF/USDT'), ('WAXP/USDT', 'WAXP/USDT'), ('NS/USDT', 'NS/USDT'), ('OSMO/USDT', 'OSMO/USDT'), ('MOBILE/USDT', 'MOBILE/USDT'), ('ANKR/USDT', 'ANKR/USDT'), ('ALICE/USDT', 'ALICE/USDT')])),
                ('price', models.DecimalField(decimal_places=18, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('fee', models.DecimalField(decimal_places=18, default=0.0, max_digits=30)),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangeclient')),
            ],
            options={
                'verbose_name': 'Ордер Клиента Биржи',
                'verbose_name_plural': 'Ордеры Клиента Биржи',
            },
        ),
        migrations.AddField(
            model_name='exchangeclient',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchanges.proxy'),
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Временная метка')),
                ('high', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Максимальная цена за период свечи')),
                ('low', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Минимальная цена за период свечи')),
                ('open', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена открытия свечи')),
                ('close', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена закрытия свечи')),
                ('volume', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Объём за период свечи')),
                ('candle_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.candlesource')),
            ],
            options={
                'verbose_name': 'Свеча',
                'verbose_name_plural': 'Свечи',
                'constraints': [models.UniqueConstraint(fields=('candle_source', 'timestamp'), name='unique_candle_source_timestamp')],
            },
        ),
        migrations.AddConstraint(
            model_name='candlesource',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timeframe'), name='unique_exchange_pair_timeframe'),
        ),
        migrations.AddConstraint(
            model_name='exchangeorder',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'exchange_order_id'), name='unique_exchange_client_and_exchange_order_id'),
        ),
        migrations.AddConstraint(
            model_name='exchangeclient',
            constraint=models.UniqueConstraint(fields=('api_key', 'api_secret'), name='unique_api_key_api_secret'),
        ),
    ]
