# Generated by Django 5.2.6 on 2026-05-03 09:19

import django.db.models.deletion
import exchanges.domain.schemas
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('class_name', models.CharField(choices=exchanges.domain.schemas.ExchangeRegistry.get_choices, max_length=30, unique=True, verbose_name='Класс биржи')),
                ('max_candles_per_request', models.PositiveIntegerField(default=999, help_text='Максимальное количество свечей за один запрос к API биржи', verbose_name='Лимит загрузки свечей')),
                ('timeout', models.PositiveIntegerField(default=30000, help_text='Максимальное время ожидания ответа от API биржи', verbose_name='Таймаут (мс)')),
                ('rate_limit', models.PositiveIntegerField(default=500, help_text='Минимальный интервал между запросами к API биржи', verbose_name='Rate limit (мс)')),
                ('candle_source_mode', models.CharField(choices=[('rest', 'REST'), ('ws', 'WebSocket')], default='ws', max_length=4, verbose_name='Режим получения свечей')),
                ('market_types', models.JSONField(default=list, verbose_name='Типы рынков')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
            },
        ),
        migrations.CreateModel(
            name='ExchangeTradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('base_currency', models.CharField(help_text='BTC в BTC/USDT', max_length=20, verbose_name='Базовая валюта')),
                ('quote_currency', models.CharField(help_text='USDT в BTC/USDT', max_length=20, verbose_name='Валюта котировки')),
                ('settle_currency', models.CharField(blank=True, default='', help_text='USDT в BTC/USDT:USDT (только для фьючерсов)', max_length=20, verbose_name='Валюта расчёта')),
                ('type', models.CharField(choices=[('futures', 'Futures'), ('spot', 'Spot')], max_length=10, verbose_name='Тип рынка')),
                ('is_linear', models.BooleanField(blank=True, help_text='True — линейный (USDT-margined), False — инверсный (coin-margined)', null=True, verbose_name='Линейный контракт')),
                ('symbol', models.CharField(default='BTC/USDT:USDT', max_length=50, verbose_name='Символ')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Минимальное количество')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Максимальное количество')),
                ('min_cost', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Минимальная стоимость ордера')),
                ('max_cost', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Максимальная стоимость ордера')),
                ('min_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Минимальная цена ордера')),
                ('max_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Максимальная цена ордера')),
                ('price_precision', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Точность цены')),
                ('amount_precision', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Точность количества')),
                ('taker_fee', models.DecimalField(decimal_places=5, default=Decimal('0.001'), help_text='Коэффициент, например 0.001 = 0.1%', max_digits=6, verbose_name='Комиссия Taker')),
                ('maker_fee', models.DecimalField(decimal_places=5, default=Decimal('0.001'), help_text='Коэффициент, например 0.001 = 0.1%', max_digits=6, verbose_name='Комиссия Maker')),
                ('min_leverage', models.DecimalField(decimal_places=1, default=Decimal('1'), help_text='Например 1 для 1x', max_digits=6, verbose_name='Минимальное плечо')),
                ('max_leverage', models.DecimalField(decimal_places=1, default=Decimal('1'), help_text='Например 125 для 125x', max_digits=6, verbose_name='Максимальное плечо')),
                ('contract_size', models.DecimalField(blank=True, decimal_places=18, help_text='Размер одного контракта в base currency', max_digits=30, null=True, verbose_name='Размер контракта')),
                ('supports_cross_margin', models.BooleanField(default=False, verbose_name='Поддержка cross margin')),
                ('supports_isolated_margin', models.BooleanField(default=False, verbose_name='Поддержка isolated margin')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_pairs', to='exchanges.exchange', verbose_name='Биржа')),
            ],
            options={
                'verbose_name': 'Торговая пара биржи',
                'verbose_name_plural': 'Торговые пары бирж',
            },
        ),
        migrations.CreateModel(
            name='ExchangeCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Максимальная цена')),
                ('low', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Минимальная цена')),
                ('open', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена открытия')),
                ('close', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена закрытия')),
                ('volume', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='Объём торгов')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], max_length=3, verbose_name='Таймфрейм')),
                ('timestamp', models.DateTimeField(verbose_name='Временная метка')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangetradingpair', verbose_name='Торговая пара биржи')),
            ],
            options={
                'verbose_name': 'Свеча биржи',
                'verbose_name_plural': 'Свечи бирж',
            },
        ),
        migrations.AddConstraint(
            model_name='exchangetradingpair',
            constraint=models.UniqueConstraint(fields=('exchange', 'name', 'type'), name='unique_exchange_trading_pair'),
        ),
        migrations.AddConstraint(
            model_name='exchangecandle',
            constraint=models.UniqueConstraint(fields=('timeframe', 'trading_pair', 'timestamp'), name='unique_candle'),
        ),
    ]
