# Generated by Django 5.2.6 on 2026-02-08
# Data migration to populate Exchange and TradingPair objects

from decimal import Decimal

from django.db import migrations


def populate_exchanges_and_pairs(apps, schema_editor):
    Exchange = apps.get_model("exchanges", "Exchange")
    TradingPair = apps.get_model("exchanges", "TradingPair")

    # Exchanges with their class names and candle fetch limits
    exchanges_data = [
        {
            "name": "Binance",
            "class_name": "BinanceExchangeClient",
            "candle_fetch_limit": 1000,
        },
        {
            "name": "Bybit",
            "class_name": "ByBitExchangeClient",
            "candle_fetch_limit": 1000,
        },
        {
            "name": "OKX",
            "class_name": "OKXExchangeClient",
            "candle_fetch_limit": 300,
        },
        {
            "name": "Kraken",
            "class_name": "KrakenExchangeClient",
            "candle_fetch_limit": 720,
        },
        {
            "name": "Bitget",
            "class_name": "BitgetExchangeClient",
            "candle_fetch_limit": 1000,
        },
        {
            "name": "Coinbase",
            "class_name": "CoinbaseExchangeClient",
            "candle_fetch_limit": 300,
        },
        {
            "name": "KuCoin",
            "class_name": "KuCoinExchangeClient",
            "candle_fetch_limit": 1500,
        },
        {
            "name": "Gate.io",
            "class_name": "GateIOExchangeClient",
            "candle_fetch_limit": 1000,
        },
        {
            "name": "HTX",
            "class_name": "HTXExchangeClient",
            "candle_fetch_limit": 2000,
        },
        {
            "name": "MEXC",
            "class_name": "MEXCExchangeClient",
            "candle_fetch_limit": 1000,
        },
        {
            "name": "Phemex",
            "class_name": "PhemexExchangeClient",
            "candle_fetch_limit": 1000,
        },
        {
            "name": "Deribit",
            "class_name": "DeribitExchangeClient",
            "candle_fetch_limit": 5000,
        },
        {
            "name": "BitMEX",
            "class_name": "BitMEXExchangeClient",
            "candle_fetch_limit": 1000,
        },
        {
            "name": "Bitfinex",
            "class_name": "BitfinexExchangeClient",
            "candle_fetch_limit": 10000,
        },
    ]

    for exchange_data in exchanges_data:
        Exchange.objects.update_or_create(
            class_name=exchange_data["class_name"],
            defaults={
                "name": exchange_data["name"],
                "candle_fetch_limit": exchange_data["candle_fetch_limit"],
            },
        )

    # Popular trading pairs (~50 pairs)
    trading_pairs_data = [
        # Major cryptocurrencies
        ("BTC/USDT", "BTC/USDT:USDT", "0.001", "1000"),
        ("ETH/USDT", "ETH/USDT:USDT", "0.01", "10000"),
        ("BNB/USDT", "BNB/USDT:USDT", "0.01", "10000"),
        ("XRP/USDT", "XRP/USDT:USDT", "1", "1000000"),
        ("SOL/USDT", "SOL/USDT:USDT", "0.1", "100000"),
        ("ADA/USDT", "ADA/USDT:USDT", "1", "1000000"),
        ("DOGE/USDT", "DOGE/USDT:USDT", "1", "10000000"),
        ("TRX/USDT", "TRX/USDT:USDT", "1", "10000000"),
        ("AVAX/USDT", "AVAX/USDT:USDT", "0.1", "100000"),
        ("DOT/USDT", "DOT/USDT:USDT", "0.1", "100000"),
        # Layer 1 & 2
        ("MATIC/USDT", "MATIC/USDT:USDT", "1", "1000000"),
        ("LINK/USDT", "LINK/USDT:USDT", "0.1", "100000"),
        ("ATOM/USDT", "ATOM/USDT:USDT", "0.1", "100000"),
        ("LTC/USDT", "LTC/USDT:USDT", "0.01", "10000"),
        ("UNI/USDT", "UNI/USDT:USDT", "0.1", "100000"),
        ("BCH/USDT", "BCH/USDT:USDT", "0.01", "10000"),
        ("ETC/USDT", "ETC/USDT:USDT", "0.1", "100000"),
        ("NEAR/USDT", "NEAR/USDT:USDT", "0.1", "100000"),
        ("FIL/USDT", "FIL/USDT:USDT", "0.1", "100000"),
        ("APT/USDT", "APT/USDT:USDT", "0.1", "100000"),
        # DeFi tokens
        ("AAVE/USDT", "AAVE/USDT:USDT", "0.01", "10000"),
        ("CRV/USDT", "CRV/USDT:USDT", "1", "1000000"),
        ("MKR/USDT", "MKR/USDT:USDT", "0.001", "1000"),
        ("SNX/USDT", "SNX/USDT:USDT", "0.1", "100000"),
        ("COMP/USDT", "COMP/USDT:USDT", "0.01", "10000"),
        ("LDO/USDT", "LDO/USDT:USDT", "1", "1000000"),
        ("SUSHI/USDT", "SUSHI/USDT:USDT", "1", "1000000"),
        ("1INCH/USDT", "1INCH/USDT:USDT", "1", "1000000"),
        # Gaming & Metaverse
        ("SAND/USDT", "SAND/USDT:USDT", "1", "1000000"),
        ("MANA/USDT", "MANA/USDT:USDT", "1", "1000000"),
        ("AXS/USDT", "AXS/USDT:USDT", "0.1", "100000"),
        ("ENJ/USDT", "ENJ/USDT:USDT", "1", "1000000"),
        ("GALA/USDT", "GALA/USDT:USDT", "10", "10000000"),
        ("IMX/USDT", "IMX/USDT:USDT", "1", "1000000"),
        # Infrastructure & Oracle
        ("GRT/USDT", "GRT/USDT:USDT", "1", "1000000"),
        ("FET/USDT", "FET/USDT:USDT", "1", "1000000"),
        ("RNDR/USDT", "RNDR/USDT:USDT", "0.1", "100000"),
        ("INJ/USDT", "INJ/USDT:USDT", "0.1", "100000"),
        ("AR/USDT", "AR/USDT:USDT", "0.1", "100000"),
        # Exchange tokens
        ("FTT/USDT", "FTT/USDT:USDT", "0.1", "100000"),
        ("OKB/USDT", "OKB/USDT:USDT", "0.1", "100000"),
        ("CRO/USDT", "CRO/USDT:USDT", "1", "10000000"),
        # Meme coins
        ("SHIB/USDT", "SHIB/USDT:USDT", "100000", "100000000000"),
        ("PEPE/USDT", "PEPE/USDT:USDT", "1000000", "100000000000"),
        ("FLOKI/USDT", "FLOKI/USDT:USDT", "10000", "100000000000"),
        ("WIF/USDT", "WIF/USDT:USDT", "1", "1000000"),
        ("BONK/USDT", "BONK/USDT:USDT", "100000", "100000000000"),
        # Other popular
        ("OP/USDT", "OP/USDT:USDT", "0.1", "100000"),
        ("ARB/USDT", "ARB/USDT:USDT", "0.1", "100000"),
        ("SUI/USDT", "SUI/USDT:USDT", "1", "1000000"),
        ("SEI/USDT", "SEI/USDT:USDT", "1", "1000000"),
        ("TIA/USDT", "TIA/USDT:USDT", "0.1", "100000"),
    ]

    for name, symbol, min_amount, max_amount in trading_pairs_data:
        TradingPair.objects.get_or_create(
            name=name,
            defaults={
                "symbol": symbol,
                "min_amount": Decimal(min_amount),
                "max_amount": Decimal(max_amount),
                "fee_percent": Decimal("0.1"),
            },
        )

    # ExchangeTradingPair for exchanges with different symbol formats
    ExchangeTradingPair = apps.get_model("exchanges", "ExchangeTradingPair")

    kraken_exchange = Exchange.objects.filter(name="Kraken").first()
    btc_usdt_pair = TradingPair.objects.filter(name="BTC/USDT").first()
    eth_usdt_pair = TradingPair.objects.filter(name="ETH/USDT").first()

    if kraken_exchange and btc_usdt_pair:
        ExchangeTradingPair.objects.get_or_create(
            exchange=kraken_exchange,
            trading_pair=btc_usdt_pair,
            defaults={
                "symbol": "PF_XBTUSD",
                "min_amount": Decimal("0.001"),
                "max_amount": Decimal("1000"),
                "fee_percent": Decimal("0.02"),
            },
        )
    if kraken_exchange and eth_usdt_pair:
        ExchangeTradingPair.objects.get_or_create(
            exchange=kraken_exchange,
            trading_pair=eth_usdt_pair,
            defaults={
                "symbol": "PF_ETHUSD",
                "min_amount": Decimal("0.01"),
                "max_amount": Decimal("10000"),
                "fee_percent": Decimal("0.02"),
            },
        )

    deribit_exchange = Exchange.objects.filter(name="Deribit").first()

    if deribit_exchange and btc_usdt_pair:
        ExchangeTradingPair.objects.get_or_create(
            exchange=deribit_exchange,
            trading_pair=btc_usdt_pair,
            defaults={
                "symbol": "BTC-PERPETUAL",
                "min_amount": Decimal("0.001"),
                "max_amount": Decimal("1000"),
                "fee_percent": Decimal("0.05"),
            },
        )
    if deribit_exchange and eth_usdt_pair:
        ExchangeTradingPair.objects.get_or_create(
            exchange=deribit_exchange,
            trading_pair=eth_usdt_pair,
            defaults={
                "symbol": "ETH-PERPETUAL",
                "min_amount": Decimal("0.01"),
                "max_amount": Decimal("10000"),
                "fee_percent": Decimal("0.05"),
            },
        )


def reverse_populate(apps, schema_editor):
    Exchange = apps.get_model("exchanges", "Exchange")
    TradingPair = apps.get_model("exchanges", "TradingPair")
    ExchangeTradingPair = apps.get_model("exchanges", "ExchangeTradingPair")

    ExchangeTradingPair.objects.filter(
        symbol__in=["PF_XBTUSD", "PF_ETHUSD", "BTC-PERPETUAL", "ETH-PERPETUAL"]
    ).delete()

    exchange_names = [
        "Binance", "Bybit", "OKX", "Kraken", "Bitget",
        "Coinbase", "KuCoin", "Gate.io", "HTX", "MEXC",
        "Phemex", "Deribit", "BitMEX", "Bitfinex",
    ]
    Exchange.objects.filter(name__in=exchange_names).delete()

    pair_names = [
        "BTC/USDT", "ETH/USDT", "BNB/USDT", "XRP/USDT", "SOL/USDT",
        "ADA/USDT", "DOGE/USDT", "TRX/USDT", "AVAX/USDT", "DOT/USDT",
        "MATIC/USDT", "LINK/USDT", "ATOM/USDT", "LTC/USDT", "UNI/USDT",
        "BCH/USDT", "ETC/USDT", "NEAR/USDT", "FIL/USDT", "APT/USDT",
        "AAVE/USDT", "CRV/USDT", "MKR/USDT", "SNX/USDT", "COMP/USDT",
        "LDO/USDT", "SUSHI/USDT", "1INCH/USDT", "SAND/USDT", "MANA/USDT",
        "AXS/USDT", "ENJ/USDT", "GALA/USDT", "IMX/USDT", "GRT/USDT",
        "FET/USDT", "RNDR/USDT", "INJ/USDT", "AR/USDT", "FTT/USDT",
        "OKB/USDT", "CRO/USDT", "SHIB/USDT", "PEPE/USDT", "FLOKI/USDT",
        "WIF/USDT", "BONK/USDT", "OP/USDT", "ARB/USDT", "SUI/USDT",
        "SEI/USDT", "TIA/USDT",
    ]
    TradingPair.objects.filter(name__in=pair_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("exchanges", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_exchanges_and_pairs, reverse_populate),
    ]
