# Generated by Django 5.2.1 on 2025-06-30 22:54

import django.db.models.deletion
import exchanges.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.candlesource', verbose_name='Источник свечей'),
        ),
        migrations.AlterField(
            model_name='candlesource',
            name='exchange_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangeclient', verbose_name='Клиент биржи'),
        ),
        migrations.AlterField(
            model_name='candlesource',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3, verbose_name='Таймфрейм'),
        ),
        migrations.AlterField(
            model_name='candlesource',
            name='trading_pair',
            field=models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('ADA/USDT', 'ADA/USDT'), ('XRP/USDT', 'XRP/USDT'), ('KAS/USDT', 'KAS/USDT'), ('DEEP/USDT', 'DEEP/USDT'), ('DOGE/USDT', 'DOGE/USDT'), ('LINK/USDT', 'LINK/USDT'), ('SHIB1000/USDT', 'SHIB1000/USDT'), ('AVAX/USDT', 'AVAX/USDT'), ('MLN/USDT', 'MLN/USDT'), ('DOT/USDT', 'DOT/USDT'), ('BIO/USDT', 'BIO/USDT'), ('CLOUD/USDT', 'CLOUD/USDT'), ('CORE/USDT', 'CORE/USDT'), ('RONIN/USDT', 'RONIN/USDT'), ('SHELLU/SDT', 'SHELLU/SDT'), ('SOLAYER/USDT', 'SOLAYER/USDT'), ('VIRTUAL/USDT', 'VIRTUAL/USDT'), ('ARB/USDT', 'ARB/USDT'), ('BSV/USDT', 'BSV/USDT'), ('DOGS/USDT', 'DOGS/USDT'), ('GMT/USDT', 'GMT/USDT'), ('NTRN/USDT', 'NTRN/USDT'), ('COTI/USDT', 'COTI/USDT'), ('KOMA/USDT', 'KOMA/USDT'), ('BMT/USDT', 'BMT/USDT'), ('THE/USDT', 'THE/USDT'), ('GODS/USDT', 'GODS/USDT'), ('ZRO/USDT', 'ZRO/USDT'), ('CAKE/USDT', 'CAKE/USDT'), ('TRX/USDT', 'TRX/USDT'), ('PARTI/USDT', 'PARTI/USDT'), ('XTER/USDT', 'XTER/USDT'), ('SYN/USDT', 'SYN/USDT'), ('ACX/USDT', 'ACX/USDT'), ('MAVIA/USDT', 'MAVIA/USDT'), ('XCN/USDT', 'XCN/USDT'), ('CETUS/USDT', 'CETUS/USDT'), ('AIXBT/USDT', 'AIXBT/USDT'), ('SUI/USDT', 'SUI/USDT'), ('XRD/USDT', 'XRD/USDT'), ('PROMPT/USDT', 'PROMPT/USDT'), ('SPELL/USDT', 'SPELL/USDT'), ('PNUT/USDT', 'PNUT/USDT'), ('AR/USDT', 'AR/USDT'), ('MICHI/USDT', 'MICHI/USDT'), ('MERL/USDT', 'MERL/USDT'), ('AVAIL/USDT', 'AVAIL/USDT'), ('AI/USDT', 'AI/USDT'), ('UNI/USDT', 'UNI/USDT'), ('IP/USDT', 'IP/USDT'), ('ZEN/USDT', 'ZEN/USDT'), ('AEVO/USDT', 'AEVO/USDT'), ('AI16Z/USDT', 'AI16Z/USDT'), ('LOOKS/USDT', 'LOOKS/USDT'), ('XVG/USDT', 'XVG/USDT'), ('SLERF/USDT', 'SLERF/USDT'), ('GMX/USDT', 'GMX/USDT'), ('RENDER/USDT', 'RENDER/USDT'), ('TNSR/USDT', 'TNSR/USDT'), ('GALA/USDT', 'GALA/USDT'), ('IO/USDT', 'IO/USDT'), ('RPL/USDT', 'RPL/USDT'), ('SWEAT/USDT', 'SWEAT/USDT'), ('TIA/USDT', 'TIA/USDT'), ('BLAST/USDT', 'BLAST/USDT'), ('CPOOL/USDT', 'CPOOL/USDT'), ('ONT/USDT', 'ONT/USDT'), ('ETC/USDT', 'ETC/USDT'), ('SUN/USDT', 'SUN/USDT'), ('DGB/USDT', 'DGB/USDT'), ('PORTAL/USDT', 'PORTAL/USDT'), ('STG/USDT', 'STG/USDT'), ('PIXEL/USDT', 'PIXEL/USDT'), ('S/USDT', 'S/USDT'), ('RIF/USDT', 'RIF/USDT'), ('WAXP/USDT', 'WAXP/USDT'), ('NS/USDT', 'NS/USDT'), ('OSMO/USDT', 'OSMO/USDT'), ('MOBILE/USDT', 'MOBILE/USDT'), ('ANKR/USDT', 'ANKR/USDT'), ('ALICE/USDT', 'ALICE/USDT')], max_length=20, verbose_name='Торговая пара'),
        ),
        migrations.AlterField(
            model_name='exchangeclient',
            name='api_key',
            field=models.CharField(max_length=200, verbose_name='API ключ'),
        ),
        migrations.AlterField(
            model_name='exchangeclient',
            name='api_secret',
            field=models.CharField(max_length=200, verbose_name='API секрет'),
        ),
        migrations.AlterField(
            model_name='exchangeclient',
            name='class_name',
            field=models.CharField(choices=exchanges.domain.base.ExchangeClientRegistry.get_choices, max_length=30, verbose_name='Класс клиента'),
        ),
        migrations.AlterField(
            model_name='exchangeclient',
            name='demo',
            field=models.BooleanField(default=True, verbose_name='Демо режим'),
        ),
        migrations.AlterField(
            model_name='exchangeclient',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название клиента'),
        ),
        migrations.AlterField(
            model_name='exchangeclient',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchanges.proxy', verbose_name='Прокси'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='exchange_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangeclient', verbose_name='Клиент биржи'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='exchange_order_id',
            field=models.CharField(max_length=50, verbose_name='ID ордера на бирже'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='fee',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='price',
            field=models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='side',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, verbose_name='Сторона (BUY/SELL)'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='opened', max_length=10, verbose_name='Статус ордера'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Время ордера'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='trading_pair',
            field=models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('ADA/USDT', 'ADA/USDT'), ('XRP/USDT', 'XRP/USDT'), ('KAS/USDT', 'KAS/USDT'), ('DEEP/USDT', 'DEEP/USDT'), ('DOGE/USDT', 'DOGE/USDT'), ('LINK/USDT', 'LINK/USDT'), ('SHIB1000/USDT', 'SHIB1000/USDT'), ('AVAX/USDT', 'AVAX/USDT'), ('MLN/USDT', 'MLN/USDT'), ('DOT/USDT', 'DOT/USDT'), ('BIO/USDT', 'BIO/USDT'), ('CLOUD/USDT', 'CLOUD/USDT'), ('CORE/USDT', 'CORE/USDT'), ('RONIN/USDT', 'RONIN/USDT'), ('SHELLU/SDT', 'SHELLU/SDT'), ('SOLAYER/USDT', 'SOLAYER/USDT'), ('VIRTUAL/USDT', 'VIRTUAL/USDT'), ('ARB/USDT', 'ARB/USDT'), ('BSV/USDT', 'BSV/USDT'), ('DOGS/USDT', 'DOGS/USDT'), ('GMT/USDT', 'GMT/USDT'), ('NTRN/USDT', 'NTRN/USDT'), ('COTI/USDT', 'COTI/USDT'), ('KOMA/USDT', 'KOMA/USDT'), ('BMT/USDT', 'BMT/USDT'), ('THE/USDT', 'THE/USDT'), ('GODS/USDT', 'GODS/USDT'), ('ZRO/USDT', 'ZRO/USDT'), ('CAKE/USDT', 'CAKE/USDT'), ('TRX/USDT', 'TRX/USDT'), ('PARTI/USDT', 'PARTI/USDT'), ('XTER/USDT', 'XTER/USDT'), ('SYN/USDT', 'SYN/USDT'), ('ACX/USDT', 'ACX/USDT'), ('MAVIA/USDT', 'MAVIA/USDT'), ('XCN/USDT', 'XCN/USDT'), ('CETUS/USDT', 'CETUS/USDT'), ('AIXBT/USDT', 'AIXBT/USDT'), ('SUI/USDT', 'SUI/USDT'), ('XRD/USDT', 'XRD/USDT'), ('PROMPT/USDT', 'PROMPT/USDT'), ('SPELL/USDT', 'SPELL/USDT'), ('PNUT/USDT', 'PNUT/USDT'), ('AR/USDT', 'AR/USDT'), ('MICHI/USDT', 'MICHI/USDT'), ('MERL/USDT', 'MERL/USDT'), ('AVAIL/USDT', 'AVAIL/USDT'), ('AI/USDT', 'AI/USDT'), ('UNI/USDT', 'UNI/USDT'), ('IP/USDT', 'IP/USDT'), ('ZEN/USDT', 'ZEN/USDT'), ('AEVO/USDT', 'AEVO/USDT'), ('AI16Z/USDT', 'AI16Z/USDT'), ('LOOKS/USDT', 'LOOKS/USDT'), ('XVG/USDT', 'XVG/USDT'), ('SLERF/USDT', 'SLERF/USDT'), ('GMX/USDT', 'GMX/USDT'), ('RENDER/USDT', 'RENDER/USDT'), ('TNSR/USDT', 'TNSR/USDT'), ('GALA/USDT', 'GALA/USDT'), ('IO/USDT', 'IO/USDT'), ('RPL/USDT', 'RPL/USDT'), ('SWEAT/USDT', 'SWEAT/USDT'), ('TIA/USDT', 'TIA/USDT'), ('BLAST/USDT', 'BLAST/USDT'), ('CPOOL/USDT', 'CPOOL/USDT'), ('ONT/USDT', 'ONT/USDT'), ('ETC/USDT', 'ETC/USDT'), ('SUN/USDT', 'SUN/USDT'), ('DGB/USDT', 'DGB/USDT'), ('PORTAL/USDT', 'PORTAL/USDT'), ('STG/USDT', 'STG/USDT'), ('PIXEL/USDT', 'PIXEL/USDT'), ('S/USDT', 'S/USDT'), ('RIF/USDT', 'RIF/USDT'), ('WAXP/USDT', 'WAXP/USDT'), ('NS/USDT', 'NS/USDT'), ('OSMO/USDT', 'OSMO/USDT'), ('MOBILE/USDT', 'MOBILE/USDT'), ('ANKR/USDT', 'ANKR/USDT'), ('ALICE/USDT', 'ALICE/USDT')], verbose_name='Торговая пара'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='type',
            field=models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], default='market', max_length=10, verbose_name='Тип ордера'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='errors',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибки'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.IntegerField(verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='protocol',
            field=models.CharField(choices=[('socks5', 'Socks5'), ('socks4', 'Socks4')], default='socks5', max_length=10, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
