# Generated by Django 5.2.1 on 2025-06-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='name',
            field=models.CharField(default='bybit', max_length=20),
            preserve_default=False,
        ),
    ]
