# Generated by Django 5.2.6 on 2026-02-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
    ]
