# Generated by Django 5.2.6 on 2025-12-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('traders', '0007_remove_tradersignal_unique_signal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candle',
            new_name='ExchangeCandle',
        ),
        migrations.AlterModelOptions(
            name='exchangecandle',
            options={'verbose_name': 'Свеча биржи', 'verbose_name_plural': 'Свечи бирж'},
        ),
    ]
