# Generated by Django 5.2.1 on 2025-06-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeorder',
            old_name='volume',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='exchangeorder',
            old_name='type',
            new_name='side',
        ),
        migrations.RenameField(
            model_name='exchangeorder',
            old_name='executed',
            new_name='status',
        ),
        migrations.AddConstraint(
            model_name='exchangeorder',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'timestamp'), name='unique_order_per_client_and_timestamp'),
        ),
    ]
