# Generated by Django 5.2.1 on 2025-06-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeorder',
            options={'verbose_name': 'Ордер Клиента Биржи', 'verbose_name_plural': 'Ордеры Клиента Биржи'},
        ),
    ]
