# Generated by Django 5.2.6 on 2026-05-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='rate_limit',
            field=models.PositiveIntegerField(default=100, help_text='Минимальный интервал между запросами к API биржи', verbose_name='Rate limit (мс)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='timeout',
            field=models.PositiveIntegerField(default=5000, help_text='Максимальное время ожидания ответа от API биржи', verbose_name='Таймаут (мс)'),
        ),
    ]
