# Generated by Django 5.2.1 on 2025-06-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'verbose_name': 'Свеча', 'verbose_name_plural': 'Свечи'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'verbose_name': 'Биржа', 'verbose_name_plural': 'Биржи'},
        ),
        migrations.AlterModelOptions(
            name='tradingpair',
            options={'verbose_name': 'Торговая пара', 'verbose_name_plural': 'Торговые пары'},
        ),
    ]
