# Generated by Django 5.2.1 on 2025-06-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_alter_exchangeorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='trading_pair',
            field=models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('ADA/USDT', 'ADA/USDT'), ('XRP/USDT', 'XRP/USDT'), ('KAS/USDT', 'KAS/USDT'), ('DEEP/USDT', 'DEEP/USDT'), ('DOGE/USDT', 'DOGE/USDT'), ('LINK/USDT', 'LINK/USDT'), ('SHIB1000/USDT', 'SHIB1000/USDT'), ('AVAX/USDT', 'AVAX/USDT'), ('MLN/USDT', 'MLN/USDT'), ('DOT/USDT', 'DOT/USDT')], default='BTC/USDT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candlesource',
            name='trading_pair',
            field=models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('ADA/USDT', 'ADA/USDT'), ('XRP/USDT', 'XRP/USDT'), ('KAS/USDT', 'KAS/USDT'), ('DEEP/USDT', 'DEEP/USDT'), ('DOGE/USDT', 'DOGE/USDT'), ('LINK/USDT', 'LINK/USDT'), ('SHIB1000/USDT', 'SHIB1000/USDT'), ('AVAX/USDT', 'AVAX/USDT'), ('MLN/USDT', 'MLN/USDT'), ('DOT/USDT', 'DOT/USDT')], max_length=20),
        ),
    ]
