# Generated by Django 5.2.1 on 2025-06-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_rename_volume_exchangeorder_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='open', max_length=10),
        ),
    ]
