# Generated by Django 5.2.6 on 2026-05-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_alter_exchange_rate_limit_alter_exchange_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='type',
            field=models.CharField(choices=[('futures', 'Futures'), ('spot', 'Spot'), ('index', 'Index')], max_length=10, verbose_name='Тип рынка'),
        ),
    ]
