# Generated by Django 5.2.1 on 2025-07-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_tradingpair_created_at_tradingpair_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='value',
            field=models.CharField(default='BTC/USDT:USDT', help_text='Формат:BTC/USDT:USDT', max_length=50, unique=True, verbose_name='Значение торговой пары'),
        ),
    ]
