# Generated by Django 5.2.1 on 2025-07-07 14:59

import exchanges.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_exchangeclient_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='class_name',
            field=models.CharField(choices=exchanges.domain.base.ExchangeClientRegistry.get_choices, max_length=30, unique=True, verbose_name='Класс клиента'),
        ),
    ]
