# Generated by Django 5.2.1 on 2025-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_alter_tradingpair_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeorder',
            options={'verbose_name': 'Ордер биржи', 'verbose_name_plural': 'Ордера биржи'},
        ),
        migrations.AlterField(
            model_name='candle',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Временная метка'),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Время ордера'),
        ),
    ]
