# Generated by Django 5.2.6 on 2025-10-03 20:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_alter_exchange_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='min_amount',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.001'), help_text='Минимальное количетсво для создания ордера', max_digits=30, verbose_name='Минимальное количетсво'),
        ),
    ]
