# Generated by Django 5.2.6 on 2026-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_add_woofipro_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecandle',
            name='volume',
            field=models.DecimalField(decimal_places=18, max_digits=38, verbose_name='Объём торгов'),
        ),
    ]
