# Generated by Django 5.2.1 on 2025-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_alter_exchangeorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlesource',
            name='trading_pair',
            field=models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('ADA/USDT', 'ADA/USDT')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TradingPair',
        ),
    ]
