# Generated by Django 5.2.6 on 2025-11-14 18:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_alter_tradingpair_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.1'), help_text='Процентная комиссия за сделку на данной торговой паре', max_digits=5, verbose_name='Процентная комиссия'),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='max_amount',
            field=models.DecimalField(decimal_places=18, default=Decimal('1000000'), help_text='Максимальное количетсво для создания ордера', max_digits=30, verbose_name='Максимальное количетсво'),
        ),
        migrations.CreateModel(
            name='ExchangeTradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('symbol', models.CharField(default='BTC/USDT:USDT', help_text='Формат:BTC/USDT:USDT', max_length=50, unique=True, verbose_name='Значение торговой пары')),
                ('min_amount', models.DecimalField(decimal_places=18, default=Decimal('0.001'), help_text='Минимальное количетсво для создания ордера', max_digits=30, verbose_name='Минимальное количетсво')),
                ('max_amount', models.DecimalField(decimal_places=18, default=Decimal('1000000'), help_text='Максимальное количетсво для создания ордера', max_digits=30, verbose_name='Максимальное количетсво')),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.1'), help_text='Процентная комиссия за сделку на данной торговой паре', max_digits=5, verbose_name='Процентная комиссия')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Торговая пара биржи',
                'verbose_name_plural': 'Торговые пары бирж',
                'constraints': [models.UniqueConstraint(fields=('exchange', 'trading_pair'), name='unique_exchange_trading_pair')],
            },
        ),
    ]
