# Generated by Django 5.2.1 on 2025-06-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_alter_candlesource_trading_pair_delete_tradingpair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeclient',
            options={'verbose_name': 'Клиент Биржи', 'verbose_name_plural': 'Клиенты Бирж'},
        ),
        migrations.AlterModelOptions(
            name='exchangeorder',
            options={'verbose_name': 'История Клиента', 'verbose_name_plural': 'Истории Клиента'},
        ),
    ]
