# Generated by Django 5.2.1 on 2025-07-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_alter_exchangeorder_options_alter_candle_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingpair',
            old_name='value',
            new_name='symbol',
        ),
    ]
