# Generated by Django 5.2.1 on 2025-06-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_alter_candlesource_trading_pair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlesource',
            name='exchange_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangeclient'),
        ),
    ]
