# Generated by Django 5.2.1 on 2025-07-07 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_alter_exchange_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа'),
            preserve_default=False,
        ),
    ]
