# Generated by Django 5.2.1 on 2025-07-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_rename_value_tradingpair_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeorder',
            name='exchange_order_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='ID ордера на бирже'),
        ),
    ]
