# Generated by Django 5.2.6 on 2026-03-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_rename_candle_fetch_limit_to_max_candles_per_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='type',
            field=models.CharField(choices=[('futures', 'Futures'), ('spot', 'Spot')], default='futures', max_length=10, verbose_name='Тип рынка'),
        ),
    ]
