# Generated by Django 5.2.1 on 2025-06-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_alter_exchangeclient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='type',
            field=models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], default='market', max_length=10),
        ),
    ]
