# Generated by Django 5.2.1 on 2025-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_candle_exchange'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candle',
            name='unique_candle_source_timestamp',
        ),
        migrations.AddField(
            model_name='candle',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3, verbose_name='Таймфрейм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='trading_pair',
            field=models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('ADA/USDT', 'ADA/USDT'), ('XRP/USDT', 'XRP/USDT'), ('KAS/USDT', 'KAS/USDT'), ('DEEP/USDT', 'DEEP/USDT'), ('DOGE/USDT', 'DOGE/USDT'), ('LINK/USDT', 'LINK/USDT'), ('SHIB1000/USDT', 'SHIB1000/USDT'), ('AVAX/USDT', 'AVAX/USDT'), ('MLN/USDT', 'MLN/USDT'), ('DOT/USDT', 'DOT/USDT'), ('BIO/USDT', 'BIO/USDT'), ('CLOUD/USDT', 'CLOUD/USDT'), ('CORE/USDT', 'CORE/USDT'), ('RONIN/USDT', 'RONIN/USDT'), ('SHELLU/SDT', 'SHELLU/SDT'), ('SOLAYER/USDT', 'SOLAYER/USDT'), ('VIRTUAL/USDT', 'VIRTUAL/USDT'), ('ARB/USDT', 'ARB/USDT'), ('BSV/USDT', 'BSV/USDT'), ('DOGS/USDT', 'DOGS/USDT'), ('GMT/USDT', 'GMT/USDT'), ('NTRN/USDT', 'NTRN/USDT'), ('COTI/USDT', 'COTI/USDT'), ('KOMA/USDT', 'KOMA/USDT'), ('BMT/USDT', 'BMT/USDT'), ('THE/USDT', 'THE/USDT'), ('GODS/USDT', 'GODS/USDT'), ('ZRO/USDT', 'ZRO/USDT'), ('CAKE/USDT', 'CAKE/USDT'), ('TRX/USDT', 'TRX/USDT'), ('PARTI/USDT', 'PARTI/USDT'), ('XTER/USDT', 'XTER/USDT'), ('SYN/USDT', 'SYN/USDT'), ('ACX/USDT', 'ACX/USDT'), ('MAVIA/USDT', 'MAVIA/USDT'), ('XCN/USDT', 'XCN/USDT'), ('CETUS/USDT', 'CETUS/USDT'), ('AIXBT/USDT', 'AIXBT/USDT'), ('SUI/USDT', 'SUI/USDT'), ('XRD/USDT', 'XRD/USDT'), ('PROMPT/USDT', 'PROMPT/USDT'), ('SPELL/USDT', 'SPELL/USDT'), ('PNUT/USDT', 'PNUT/USDT'), ('AR/USDT', 'AR/USDT'), ('MICHI/USDT', 'MICHI/USDT'), ('MERL/USDT', 'MERL/USDT'), ('AVAIL/USDT', 'AVAIL/USDT'), ('AI/USDT', 'AI/USDT'), ('UNI/USDT', 'UNI/USDT'), ('IP/USDT', 'IP/USDT'), ('ZEN/USDT', 'ZEN/USDT'), ('AEVO/USDT', 'AEVO/USDT'), ('AI16Z/USDT', 'AI16Z/USDT'), ('LOOKS/USDT', 'LOOKS/USDT'), ('XVG/USDT', 'XVG/USDT'), ('SLERF/USDT', 'SLERF/USDT'), ('GMX/USDT', 'GMX/USDT'), ('RENDER/USDT', 'RENDER/USDT'), ('TNSR/USDT', 'TNSR/USDT'), ('GALA/USDT', 'GALA/USDT'), ('IO/USDT', 'IO/USDT'), ('RPL/USDT', 'RPL/USDT'), ('SWEAT/USDT', 'SWEAT/USDT'), ('TIA/USDT', 'TIA/USDT'), ('BLAST/USDT', 'BLAST/USDT'), ('CPOOL/USDT', 'CPOOL/USDT'), ('ONT/USDT', 'ONT/USDT'), ('ETC/USDT', 'ETC/USDT'), ('SUN/USDT', 'SUN/USDT'), ('DGB/USDT', 'DGB/USDT'), ('PORTAL/USDT', 'PORTAL/USDT'), ('STG/USDT', 'STG/USDT'), ('PIXEL/USDT', 'PIXEL/USDT'), ('S/USDT', 'S/USDT'), ('RIF/USDT', 'RIF/USDT'), ('WAXP/USDT', 'WAXP/USDT'), ('NS/USDT', 'NS/USDT'), ('OSMO/USDT', 'OSMO/USDT'), ('MOBILE/USDT', 'MOBILE/USDT'), ('ANKR/USDT', 'ANKR/USDT'), ('ALICE/USDT', 'ALICE/USDT')], default='BTC/USDT', max_length=20, verbose_name='Торговая пара'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(fields=('exchange', 'trading_pair', 'timeframe', 'timestamp'), name='unique_candle'),
        ),
    ]
