# Generated by Django 5.2.1 on 2025-07-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0006_remove_candle_unique_candle_source_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candle',
            name='unique_candle',
        ),
    ]
