# Generated by Django 5.2.6 on 2026-03-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0006_tradingpair_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='name',
            field=models.CharField(default='BTC/USDT', max_length=50, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='tradingpair',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_trading_pair'),
        ),
    ]
