# Generated by Django 5.2.1 on 2025-07-26 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0006_alter_exchangeorder_exchange_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='min_amount',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.001'), help_text='Минимальный объем для создания ордера', max_digits=30, verbose_name='Минимальный объем'),
        ),
    ]
