# Generated by Django 5.2.1 on 2025-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0006_exchangeorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='exchange_order_id',
            field=models.CharField(default='order', max_length=50),
            preserve_default=False,
        ),
    ]
