# Generated by Django 5.2.1 on 2025-07-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0007_remove_candle_unique_candle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='candle_source',
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(fields=('exchange', 'trading_pair', 'timeframe', 'timestamp'), name='unique_candle'),
        ),
    ]
