# Generated by Django 5.2.1 on 2025-08-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0007_tradingpair_min_amount'),
        ('traders', '0012_alter_trader_exchange_client_alter_traderorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeclient',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='exchangeclient',
            name='proxy',
        ),
        migrations.RemoveField(
            model_name='exchangeclientbalance',
            name='exchange_client',
        ),
        migrations.RemoveField(
            model_name='exchangeorder',
            name='exchange_client',
        ),
        migrations.RemoveField(
            model_name='exchangeorder',
            name='trading_pair',
        ),
        migrations.DeleteModel(
            name='CandleSource',
        ),
        migrations.DeleteModel(
            name='Proxy',
        ),
        migrations.DeleteModel(
            name='ExchangeClientBalance',
        ),
        migrations.DeleteModel(
            name='ExchangeClient',
        ),
        migrations.DeleteModel(
            name='ExchangeOrder',
        ),
    ]
