# Generated by Django 5.2.6 on 2026-03-07 20:27

import exchanges.domain.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0007_alter_tradingpair_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='class_name',
            field=models.CharField(choices=exchanges.domain.schemas.ExchangeRegistry.get_choices, max_length=30, unique=True, verbose_name='Класс биржи'),
        ),
    ]
