# Generated by Django 5.2.1 on 2025-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0007_exchangeorder_exchange_order_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangeorder',
            name='unique_order_per_client_and_timestamp',
        ),
        migrations.AddConstraint(
            model_name='exchangeorder',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'timestamp', 'exchange_order_id'), name='unique_exchange_client_and_timestamp_and_exchange_order_id'),
        ),
    ]
