# Generated by Django 5.2.1 on 2025-07-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0008_remove_candle_candle_source_candle_unique_candle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candle',
            name='unique_candle',
        ),
    ]
