# Generated by Django 5.2.6 on 2026-03-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0009_update_exchange_class_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='rate_limit',
            field=models.PositiveIntegerField(default=500, verbose_name='Rate limit (мс)'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='timeout',
            field=models.PositiveIntegerField(default=30000, verbose_name='Таймаут (мс)'),
        ),
    ]
