# Generated by Django 5.2.6 on 2026-03-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0010_add_timeout_rate_limit_to_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_pairs', to='exchanges.exchange', verbose_name='Биржа'),
        ),
    ]
