# Generated by Django 5.2.1 on 2025-07-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0010_candle_unique_candle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeclient',
            name='class_name',
        ),
    ]
