# Generated by Django 5.2.6 on 2026-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0011_alter_exchangetradingpair_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='max_candles_per_request',
            field=models.PositiveIntegerField(default=999, help_text='Максимальное количество свечей за один запрос к API биржи', verbose_name='Лимит загрузки свечей'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='rate_limit',
            field=models.PositiveIntegerField(default=500, help_text='Минимальный интервал между запросами к API биржи', verbose_name='Rate limit (мс)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='timeout',
            field=models.PositiveIntegerField(default=30000, help_text='Максимальное время ожидания ответа от API биржи', verbose_name='Таймаут (мс)'),
        ),
    ]
