# Generated by Django 5.2.1 on 2025-07-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0011_remove_exchangeclient_class_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candle',
            name='unique_candle',
        ),
        migrations.RemoveConstraint(
            model_name='exchangeclient',
            name='unique_api_key_api_secret',
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(fields=('exchange', 'timeframe', 'trading_pair', 'timestamp'), name='unique_candle_constraint'),
        ),
        migrations.AddConstraint(
            model_name='exchangeclient',
            constraint=models.UniqueConstraint(fields=('api_key', 'api_secret'), name='unique_exchange_client_constraint'),
        ),
    ]
