# Generated by Django 5.2.6 on 2026-03-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0012_alter_exchange_max_candles_per_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Максимальное количество'),
        ),
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Минимальное количество'),
        ),
    ]
