# Generated by Django 5.2.1 on 2025-07-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0012_remove_candle_unique_candle_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangeorder',
            name='unique_exchange_client_and_exchange_order_id',
        ),
        migrations.AddConstraint(
            model_name='exchangeorder',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timestamp', 'exchange_order_id'), name='unique_exchange_order'),
        ),
    ]
