# Generated by Django 5.2.1 on 2025-07-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0013_remove_exchangeorder_unique_exchange_client_and_exchange_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество')),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangeclient', verbose_name='Клиент биржи')),
            ],
            options={
                'verbose_name': 'Баланс Клиента Биржи',
                'verbose_name_plural': 'Балансы Клиентов Бирж',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'currency'), name='unique_balance_constraint')],
            },
        ),
    ]
