# Generated by Django 5.2.6 on 2026-03-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0013_alter_exchangetradingpair_max_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetradingpair',
            name='maker_fee',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Коэффициент, например 0.0002 = 0.02%', max_digits=10, null=True, verbose_name='Комиссия Maker'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='taker_fee',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Коэффициент, например 0.0005 = 0.05%', max_digits=10, null=True, verbose_name='Комиссия Taker'),
        ),
    ]
