# Generated by Django 5.2.6 on 2026-03-28 20:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0014_exchangetradingpair_maker_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetradingpair',
            name='max_leverage',
            field=models.PositiveIntegerField(default=1, help_text='Например 125 для 125x', verbose_name='Максимальное плечо'),
        ),
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='maker_fee',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Коэффициент, например 0.0002 = 0.02%', max_digits=10, verbose_name='Комиссия Maker'),
        ),
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='taker_fee',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Коэффициент, например 0.0005 = 0.05%', max_digits=10, verbose_name='Комиссия Taker'),
        ),
    ]
