# Generated by Django 5.2.6 on 2026-03-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0015_exchangetradingpair_max_leverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='symbol',
            field=models.CharField(default='BTC/USDT:USDT', max_length=50, verbose_name='Символ'),
        ),
    ]
