# Generated by Django 5.2.6 on 2026-03-28 20:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0016_alter_exchangetradingpair_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='maker_fee',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.001'), help_text='Коэффициент, например 0.001 = 0.1%', max_digits=10, verbose_name='Комиссия Maker'),
        ),
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='max_leverage',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), help_text='Например 125 для 125x', max_digits=4, verbose_name='Максимальное плечо'),
        ),
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='taker_fee',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.001'), help_text='Коэффициент, например 0.001 = 0.1%', max_digits=10, verbose_name='Комиссия Taker'),
        ),
    ]
