# Generated by Django 5.2.6 on 2026-03-28 20:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0017_alter_exchangetradingpair_maker_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='maker_fee',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.001'), help_text='Коэффициент, например 0.001 = 0.1%', max_digits=6, verbose_name='Комиссия Maker'),
        ),
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='taker_fee',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.001'), help_text='Коэффициент, например 0.001 = 0.1%', max_digits=6, verbose_name='Комиссия Taker'),
        ),
    ]
