# Generated by Django 5.2.6 on 2026-03-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0018_alter_exchangetradingpair_maker_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangetradingpair',
            name='fee_percent',
        ),
    ]
