# Generated by Django 5.2.6 on 2026-03-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0019_remove_exchangetradingpair_fee_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingpair',
            name='fee_percent',
        ),
        migrations.RemoveField(
            model_name='tradingpair',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='tradingpair',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='tradingpair',
            name='symbol',
        ),
    ]
