# Generated by Django 5.2.6 on 2026-03-28 23:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0020_remove_tradingpair_fee_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetradingpair',
            name='max_leverage',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), help_text='Например 125 для 125x', max_digits=6, verbose_name='Максимальное плечо'),
        ),
    ]
