# Generated by Django 5.2.6 on 2026-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0021_alter_exchangetradingpair_max_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetradingpair',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='max_cost',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Максимальная стоимость ордера'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Максимальная цена ордера'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='min_cost',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Минимальная стоимость ордера'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Минимальная цена ордера'),
        ),
    ]
