# Generated by Django 5.2.6 on 2026-03-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0022_exchangetradingpair_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetradingpair',
            name='amount_precision',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Точность количества'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='price_precision',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Точность цены'),
        ),
    ]
