# Generated by Django 5.2.6 on 2026-04-01 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0023_exchangetradingpair_amount_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetradingpair',
            name='min_leverage',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), help_text='Например 1 для 1x', max_digits=6, verbose_name='Минимальное плечо'),
        ),
    ]
