# Generated by Django 5.2.6 on 2026-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0024_add_min_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='candle_source_mode',
            field=models.CharField(choices=[('rest', 'REST'), ('ws', 'WebSocket')], default='ws', max_length=4, verbose_name='Режим получения свечей'),
        ),
    ]
