# Generated by Django 5.2.6 on 2026-04-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0025_exchange_candle_source_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='market_types',
            field=models.JSONField(default=list, verbose_name='Типы рынков'),
        ),
    ]
