# Generated by Django 5.2.6 on 2026-04-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0026_exchange_market_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='base_currency',
            field=models.CharField(blank=True, default='', help_text='BTC в BTC/USDT', max_length=20, verbose_name='Базовая валюта'),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='quote_currency',
            field=models.CharField(blank=True, default='', help_text='USDT в BTC/USDT', max_length=20, verbose_name='Валюта котировки'),
        ),
    ]
