# Generated by Django 5.2.6 on 2026-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0027_tradingpair_base_currency_tradingpair_quote_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='base_currency',
            field=models.CharField(help_text='BTC в BTC/USDT', max_length=20, verbose_name='Базовая валюта'),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='quote_currency',
            field=models.CharField(help_text='USDT в BTC/USDT', max_length=20, verbose_name='Валюта котировки'),
        ),
    ]
