# Generated by Django 5.2.6 on 2026-04-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0028_alter_tradingpair_base_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetradingpair',
            name='contract_size',
            field=models.DecimalField(blank=True, decimal_places=18, help_text='Размер одного контракта в base currency', max_digits=30, null=True, verbose_name='Размер контракта'),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='is_linear',
            field=models.BooleanField(blank=True, help_text='True — линейный (USDT-margined), False — инверсный (coin-margined)', null=True, verbose_name='Линейный контракт'),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='settle_currency',
            field=models.CharField(blank=True, default='', help_text='USDT в BTC/USDT:USDT (только для фьючерсов)', max_length=20, verbose_name='Валюта расчёта'),
        ),
    ]
