# Generated by Django 5.2.6 on 2026-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0029_exchangetradingpair_contract_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetradingpair',
            name='supports_cross_margin',
            field=models.BooleanField(default=False, verbose_name='Поддержка cross margin'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='supports_isolated_margin',
            field=models.BooleanField(default=False, verbose_name='Поддержка isolated margin'),
        ),
    ]
