# Generated by Django 5.2.6 on 2026-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0030_exchangetradingpair_supports_cross_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetradingpair',
            name='base_currency',
            field=models.CharField(blank=True, help_text='BTC в BTC/USDT', max_length=20, null=True, verbose_name='Базовая валюта'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='is_linear',
            field=models.BooleanField(blank=True, help_text='True — линейный (USDT-margined), False — инверсный (coin-margined)', null=True, verbose_name='Линейный контракт'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='quote_currency',
            field=models.CharField(blank=True, help_text='USDT в BTC/USDT', max_length=20, null=True, verbose_name='Валюта котировки'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='settle_currency',
            field=models.CharField(blank=True, default='', help_text='USDT в BTC/USDT:USDT (только для фьючерсов)', max_length=20, verbose_name='Валюта расчёта'),
        ),
        migrations.AddField(
            model_name='exchangetradingpair',
            name='type',
            field=models.CharField(blank=True, choices=[('futures', 'Futures'), ('spot', 'Spot')], max_length=10, null=True, verbose_name='Тип рынка'),
        ),
    ]
