# Generated by Django 5.2.6 on 2026-05-01 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0032_etp_populate_pair_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecandle',
            name='trading_pair_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exchanges.exchangetradingpair', verbose_name='Торговая пара биржи (новая FK)'),
        ),
    ]
