# Generated by Django 5.2.6 on 2025-12-24 20:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candle_providers', '0002_initial'),
        ('exchange_clients', '0001_initial'),
        ('exchanges', '0001_initial'),
        ('risk_managers', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('favorite', models.BooleanField(default=False, help_text='Отметьте, если хотите добавить трейдера в избранное.', verbose_name='Избранный трейдер')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('error', 'Error'), ('paused', 'Paused')], default='disabled', verbose_name='Статус')),
                ('use_fixed_balance', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет использовать фиксированный баланс, игнорируя заработанные/проебанные деньги.', verbose_name='Использовать фиксированный баланс')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Начальный баланс')),
                ('check_drawdown', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет проверять максимальную просадку.', verbose_name='Проверять просадку')),
                ('max_drawdown_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Максимальная допустимая просадка в процентах от начального баланса.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Макс. просадка (%)')),
                ('create_new_orders', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет создавать новые ордера согласно своей стратегии.', verbose_name='Создавать ордера биржи')),
                ('max_positions_count', models.PositiveSmallIntegerField(default=1, help_text='Максимальное количество одновременно открытых позиций.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Макс. количество позиций')),
                ('close_position_by_opposite_signal', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при получении противоположного сигнала.', verbose_name='Закрывать позиции при противоположном сигнале')),
                ('close_position_by_strategy', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при получении сигнала от стратегии.', verbose_name='Закрывать позиции по сигналу стратегии')),
                ('close_position_by_stop_loss', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при достижении Stop Loss.', verbose_name='Закрывать позиции по Stop Loss')),
                ('close_position_by_take_profit', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при достижении Take Profit.', verbose_name='Закрывать позиции по Take Profit')),
                ('trail_stop_enabled', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет использовать трейлинг-стоп для позиций.', verbose_name='Трейлинг-стоп')),
                ('last_reboot', models.DateTimeField(blank=True, help_text='Дата и время последнего перезапуска трейдера.', null=True, verbose_name='Последний перезапуск')),
                ('errors', models.TextField(blank=True, null=True)),
                ('last_error', models.DateTimeField(blank=True, help_text='Дата и время последней ошибки трейдера. ', null=True, verbose_name='Последняя ошибка')),
                ('candle_provider', models.ForeignKey(help_text='Выберите провайдер свечей (может быть exchange или arbitrage).', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='candle_providers.candleprovider', verbose_name='Провайдер свечей')),
                ('exchange_client', models.ForeignKey(help_text='Выберите клиента биржи, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
                ('risk_manager', models.ForeignKey(help_text='Выберите риск-менеджер, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='risk_managers.riskmanager', verbose_name='Риск-менеджер')),
                ('strategy', models.ForeignKey(help_text='Выберите стратегию, которую будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy', verbose_name='Стратегия')),
            ],
            options={
                'verbose_name': 'Трейдер',
                'verbose_name_plural': 'Трейдеры',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('first_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_first_trader', to='traders.trader', verbose_name='Первый трейдер')),
                ('second_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_second_trader', to='traders.trader', verbose_name='Второй трейдер')),
            ],
            options={
                'verbose_name': 'Арбитражный трейдер',
                'verbose_name_plural': 'Арбитражные трейдеры',
            },
        ),
        migrations.CreateModel(
            name='TraderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Тип')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество')),
                ('open_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена открытия')),
                ('close_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена закрытия')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Stop Loss')),
                ('take_profit', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Take Profit')),
                ('opened_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время открытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('recalculated_at', models.DateTimeField(blank=True, help_text='Время последнего обновления значений в позиции.', null=True, verbose_name='Время последнего перерасчета')),
                ('close_reason', models.CharField(blank=True, choices=[('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('opposite_signal', 'Opposite Signal'), ('strategy', 'Strategy'), ('timeout', 'Timeout'), ('manual', 'Manual')], help_text='Причина закрытия позиции, если она была закрыта.', max_length=20, null=True, verbose_name='Причина закрытия')),
                ('total_fee', models.DecimalField(decimal_places=18, default=Decimal('0.00'), max_digits=30, verbose_name='Общая комиссия')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Позиция трейдера',
                'verbose_name_plural': 'Позиции трейдера',
            },
        ),
        migrations.CreateModel(
            name='TraderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclientorder', verbose_name='Ордер биржи')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='Трейдер')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.traderposition', verbose_name='Позиция трейдера')),
            ],
            options={
                'verbose_name': 'Ордер трейдера',
                'verbose_name_plural': 'Ордера трейдера',
            },
        ),
        migrations.CreateModel(
            name='TraderSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Время')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('wait', 'Wait')], max_length=10, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена')),
                ('data', models.JSONField()),
                ('primary_candle', models.ForeignKey(blank=True, help_text='Основная свеча сигнала (всегда присутствует)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_signals', to='exchanges.exchangecandle', verbose_name='Основная свеча')),
                ('second_candle', models.ForeignKey(blank=True, help_text='Вторичная свеча (только для арбитражных сигналов)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_signals', to='exchanges.exchangecandle', verbose_name='Вторичная свеча')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Сигнал трейдера',
                'verbose_name_plural': 'Сигналы трейдера',
            },
        ),
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('candle_provider', 'exchange_client', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled'), name='unique_trader'),
        ),
        migrations.AddConstraint(
            model_name='arbitragetrader',
            constraint=models.UniqueConstraint(fields=('first_trader', 'second_trader'), name='unique_arbitrage_trader'),
        ),
        migrations.AddIndex(
            model_name='traderposition',
            index=models.Index(fields=['trader', 'status', 'opened_at'], name='trader_pos_trader_status_idx'),
        ),
        migrations.AddIndex(
            model_name='traderposition',
            index=models.Index(fields=['trader', 'status', 'closed_at'], name='trader_pos_closed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='traderposition',
            index=models.Index(fields=['trader', 'type', 'status'], name='trader_pos_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='traderposition',
            index=models.Index(fields=['status', 'closed_at'], name='trader_pos_status_closed_idx'),
        ),
        migrations.AddConstraint(
            model_name='traderposition',
            constraint=models.UniqueConstraint(fields=('trader', 'opened_at', 'type', 'amount'), name='unique_position'),
        ),
        migrations.AddConstraint(
            model_name='traderorder',
            constraint=models.UniqueConstraint(fields=('trader', 'order', 'position'), name='unique_trader_order'),
        ),
        migrations.AddIndex(
            model_name='tradersignal',
            index=models.Index(fields=['trader', '-timestamp'], name='trader_signal_trader_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='tradersignal',
            index=models.Index(fields=['primary_candle', 'second_candle'], name='trader_signal_candles_idx'),
        ),
        migrations.AddIndex(
            model_name='tradersignal',
            index=models.Index(fields=['trader', 'type', '-timestamp'], name='trader_signal_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradersignal',
            constraint=models.UniqueConstraint(fields=('trader', 'timestamp', 'type'), name='unique_trader_signal'),
        ),
    ]
