# Generated by Django 5.2.6 on 2026-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetradererror',
            name='traceback',
            field=models.TextField(blank=True, default='', verbose_name='Трассировка ошибки'),
        ),
        migrations.AlterField(
            model_name='arbitragetradererror',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тип ошибки'),
        ),
        migrations.AlterField(
            model_name='arbitragetraderposition',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('opposite_signal', 'Opposite Signal'), ('strategy', 'Strategy'), ('timeout', 'Timeout'), ('manual', 'Manual')], default='', help_text='Причина закрытия позиции, если она была закрыта.', max_length=20, verbose_name='Причина закрытия'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='errors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('opposite_signal', 'Opposite Signal'), ('strategy', 'Strategy'), ('timeout', 'Timeout'), ('manual', 'Manual')], default='', help_text='Причина закрытия позиции, если она была закрыта.', max_length=20, verbose_name='Причина закрытия'),
        ),
    ]
