# Generated by Django 5.2.1 on 2025-06-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trader',
            options={'verbose_name': 'Трейдер', 'verbose_name_plural': 'Трейдеры'},
        ),
    ]
