# Generated by Django 5.2.1 on 2025-06-30 22:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20, verbose_name='Начальный баланс'),
        ),
    ]
