# Generated by Django 5.2.1 on 2025-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderposition',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10),
        ),
    ]
