# Generated by Django 5.2.1 on 2025-06-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='open', max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='traders.trader')),
            ],
            options={
                'verbose_name': 'История Трейдера',
                'verbose_name_plural': 'Истории Трейдеров',
            },
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
