# Generated by Django 5.2.1 on 2025-07-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('error', 'Error')], default='disabled', verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='tradersignal',
            constraint=models.UniqueConstraint(fields=('trader', 'timestamp', 'type', 'price'), name='unique_signal_constraint'),
        ),
    ]
