# Generated by Django 5.2.1 on 2025-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderposition',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
