# Generated by Django 5.2.6 on 2025-12-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='arbitragetrader',
            name='unique_arbitrage_trader',
        ),
    ]
