# Generated by Django 5.2.1 on 2025-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='max_position_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Макс. количество позиций'),
        ),
    ]
