# Generated by Django 5.2.6 on 2025-12-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraderState',
        ),
    ]
