# Generated by Django 5.2.1 on 2025-09-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderorder',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traders.traderposition', verbose_name='Позиция трейдера'),
        ),
    ]
