# Generated by Django 5.2.1 on 2025-07-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='is_active',
        ),
    ]
