# Generated by Django 5.2.6 on 2025-12-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradersignal',
            name='unique_signal',
        ),
        migrations.RemoveField(
            model_name='tradersignal',
            name='candles',
        ),
        migrations.AddConstraint(
            model_name='tradersignal',
            constraint=models.UniqueConstraint(fields=('trader', 'timestamp', 'type'), name='unique_trader_signal'),
        ),
    ]
