# Generated by Django 5.2.6 on 2026-02-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='candles_lookback_count',
            field=models.PositiveSmallIntegerField(choices=[(50, '50'), (100, '100'), (200, '200'), (500, '500'), (1000, '1000'), (2000, '2000'), (5000, '5000'), (10000, '10000')], default=1000, verbose_name='Макс. количество свечей'),
        ),
    ]
