# Generated by Django 5.2.1 on 2025-06-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='strategy_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
