# Generated by Django 5.2.6 on 2026-02-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradererror',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='traders.trader', verbose_name='Трейдер'),
        ),
        migrations.AlterField(
            model_name='traderorder',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='traders.trader', verbose_name='Трейдер'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='traders.trader', verbose_name='Трейдер'),
        ),
        migrations.AlterField(
            model_name='tradersignal',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='traders.trader', verbose_name='Трейдер'),
        ),
    ]
