# Generated by Django 5.2.1 on 2025-07-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_remove_trader_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='favorite',
            field=models.BooleanField(default=False, help_text='Отметьте, если хотите добавить трейдера в избранное.', verbose_name='Избранный трейдер'),
        ),
    ]
