# Generated by Django 5.2.6 on 2026-02-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0002_remove_exchangeclientorder_unique_exchange_order_and_more'),
        ('traders', '0002_trader_candles_lookback_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='exchange_client',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='exchange_clients.exchangeclient', verbose_name='Клиент биржи'),
        ),
    ]
