# Generated by Django 5.2.6 on 2025-12-11 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0001_initial'),
        ('traders', '0002_delete_traderstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='candle_source',
            field=models.ForeignKey(help_text='Выберите источник свечей, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='candle_sources.candlesource', verbose_name='Источник свечей'),
        ),
    ]
