# Generated by Django 5.2.1 on 2025-06-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_traderorder_delete_orderhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraderOrder',
        ),
    ]
