# Generated by Django 5.2.6 on 2025-12-15 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('traders', '0002_remove_tradersignal_unique_signal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradersignal',
            name='candle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangecandle', verbose_name='Свеча'),
            preserve_default=False,
        ),
    ]
