# Generated by Django 5.2.1 on 2025-06-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_alter_trader_strategy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
