# Generated by Django 5.2.6 on 2026-02-01 17:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0001_initial'),
        ('exchange_clients', '0001_initial'),
        ('risk_managers', '0001_initial'),
        ('strategies', '0001_initial'),
        ('traders', '0002_remove_arbitragetrader_unique_arbitrage_trader'),
    ]

    operations = [
        # Delete old ArbitrageTrader model
        migrations.DeleteModel(
            name='ArbitrageTrader',
        ),
        # Create new ArbitrageTrader model
        migrations.CreateModel(
            name='ArbitrageTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('favorite', models.BooleanField(default=False, help_text='Отметьте, если хотите добавить трейдера в избранное.', verbose_name='Избранный трейдер')),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('paused', 'Paused'), ('error', 'Error'), ('rebooting', 'Rebooting')], default='disabled', verbose_name='Статус')),
                ('use_fixed_balance', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет использовать фиксированный баланс.', verbose_name='Использовать фиксированный баланс')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Начальный баланс')),
                ('check_drawdown', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет проверять максимальную просадку.', verbose_name='Проверять просадку')),
                ('max_drawdown_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Максимальная допустимая просадка в процентах от начального баланса.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Макс. просадка (%)')),
                ('create_new_orders', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет создавать новые ордера.', verbose_name='Создавать ордера биржи')),
                ('max_positions_count', models.PositiveSmallIntegerField(default=1, help_text='Максимальное количество одновременно открытых позиций.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Макс. количество позиций')),
                ('close_position_by_opposite_signal', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при противоположном сигнале.', verbose_name='Закрывать позиции при противоположном сигнале')),
                ('close_position_by_strategy', models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при сигнале от стратегии.', verbose_name='Закрывать позиции по сигналу стратегии')),
                ('first_candle_source', models.ForeignKey(help_text='Первый источник свечей для арбитражного трейдера.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_first_traders', to='candle_sources.candlesource', verbose_name='Первый источник свечей')),
                ('second_candle_source', models.ForeignKey(help_text='Второй источник свечей для арбитражного трейдера.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_second_traders', to='candle_sources.candlesource', verbose_name='Второй источник свечей')),
                ('first_exchange_client', models.ForeignKey(help_text='Основной клиент биржи для арбитражного трейдера.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_first_traders', to='exchange_clients.exchangeclient', verbose_name='Основной клиент биржи')),
                ('second_exchange_client', models.ForeignKey(help_text='Вторичный клиент биржи для арбитражного трейдера.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_second_traders', to='exchange_clients.exchangeclient', verbose_name='Вторичный клиент биржи')),
                ('risk_manager', models.ForeignKey(help_text='Выберите риск-менеджер, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='risk_managers.riskmanager', verbose_name='Риск-менеджер')),
                ('strategy', models.ForeignKey(help_text='Выберите стратегию, которую будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy', verbose_name='Стратегия')),
            ],
            options={
                'verbose_name': 'Арбитражный трейдер',
                'verbose_name_plural': 'Арбитражные трейдеры',
            },
        ),
        # Create ArbitrageTraderError model
        migrations.CreateModel(
            name='ArbitrageTraderError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('traceback', models.TextField(blank=True, null=True, verbose_name='Трассировка ошибки')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип ошибки')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='traders.arbitragetrader', verbose_name='Арбитражный трейдер')),
            ],
            options={
                'verbose_name': 'Ошибка арбитражного трейдера',
                'verbose_name_plural': 'Ошибки арбитражного трейдера',
                'ordering': ['-created_at'],
            },
        ),
        # Add index for ArbitrageTraderError
        migrations.AddIndex(
            model_name='arbitragetradererror',
            index=models.Index(fields=['trader', '-created_at'], name='arb_trader_error_idx'),
        ),
    ]
