# Generated by Django 5.2.1 on 2025-07-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_alter_trader_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
