# Generated by Django 5.2.1 on 2025-09-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_traderorder_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='close_posigion_by_strategy',
            field=models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при получении сигнала от стратегии.', verbose_name='Закрывать позиции по сигналу стратегии'),
        ),
        migrations.AddField(
            model_name='trader',
            name='close_position_by_stop_loss',
            field=models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при достижении Stop Loss.', verbose_name='Закрывать позиции по Stop Loss'),
        ),
        migrations.AddField(
            model_name='trader',
            name='close_position_by_take_profit',
            field=models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при достижении Take Profit.', verbose_name='Закрывать позиции по Take Profit'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='close_position_by_opposite_signal',
            field=models.BooleanField(default=True, help_text='Если выбрано, трейдер будет закрывать позицию при получении противоположного сигнала.', verbose_name='Закрывать позиции при противоположном сигнале'),
        ),
    ]
