# Generated by Django 5.2.1 on 2025-06-30 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_alter_candle_candle_source_and_more'),
        ('risk_managers', '0002_alter_riskmanager_arguments_and_more'),
        ('strategies', '0002_alter_strategy_arguments_alter_strategy_class_name_and_more'),
        ('traders', '0002_alter_trader_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='exchanges.candlesource', verbose_name='Источник свечей'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Внутренние данные'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='risk_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_managers.riskmanager', verbose_name='Риск-менеджер'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting')], default='disabled', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy', verbose_name='Стратегия'),
        ),
        migrations.AlterField(
            model_name='traderorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangeorder', verbose_name='Ордер биржи'),
        ),
        migrations.AlterField(
            model_name='traderorder',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='Трейдер'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена закрытия'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена открытия'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Stop Loss'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Take Profit'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='Трейдер'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='type',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='tradersignal',
            name='price',
            field=models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tradersignal',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='tradersignal',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='Трейдер'),
        ),
        migrations.AlterField(
            model_name='tradersignal',
            name='type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('wait', 'Wait')], max_length=10, verbose_name='Тип'),
        ),
    ]
