# Generated by Django 5.2.1 on 2025-06-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_alter_traderposition_opened_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traderposition',
            options={'verbose_name': 'Позиция трейдера', 'verbose_name_plural': 'Позиции трейдера'},
        ),
        migrations.AlterModelOptions(
            name='tradersignal',
            options={'verbose_name': 'Сигнал трейдера', 'verbose_name_plural': 'Сигналы трейдера'},
        ),
    ]
