# Generated by Django 5.2.1 on 2025-06-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_trader_max_position_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='max_position_count',
        ),
        migrations.AddField(
            model_name='trader',
            name='max_positions_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Макс. количество позиций'),
        ),
    ]
