# Generated by Django 5.2.1 on 2025-06-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_remove_trader_position_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionTrader',
            new_name='TraderPosition',
        ),
    ]
