# Generated by Django 5.2.1 on 2025-06-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_candlesource'),
        ('traders', '0002_remove_trader_exchange_remove_trader_timeframe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='candle_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exchanges.candlesource'),
            preserve_default=False,
        ),
    ]
