# Generated by Django 5.2.6 on 2026-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0003_add_related_name_to_exchange_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradererror',
            name='traceback',
            field=models.TextField(blank=True, default='', verbose_name='Traceback'),
        ),
        migrations.AlterField(
            model_name='traderoptimizererror',
            name='traceback',
            field=models.TextField(blank=True, default='', verbose_name='Traceback'),
        ),
    ]
