# Generated by Django 5.2.6 on 2025-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0003_alter_trader_candle_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='use_fixed_balance',
            field=models.BooleanField(default=False, help_text='Если выбрано, трейдер будет использовать фиксированный баланс, игнорируя заработанные/проебанные деньги.', verbose_name='Использовать фиксированный баланс'),
        ),
    ]
