# Generated by Django 5.2.6 on 2025-12-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0001_initial'),
        ('exchanges', '0001_initial'),
        ('traders', '0003_tradersignal_candle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradersignal',
            name='candle',
        ),
        migrations.AddField(
            model_name='tradersignal',
            name='candles',
            field=models.ManyToManyField(to='exchanges.exchangecandle', verbose_name='Свечи'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='candle_source',
            field=models.ForeignKey(help_text='Выберите источник свечей (может быть синтетическим), который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='candle_sources.candlesource', verbose_name='Источник свечей'),
        ),
    ]
