# Generated by Django 5.2.1 on 2025-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_alter_exchangeorder_options'),
        ('risk_managers', '0002_alter_riskmanager_options'),
        ('strategies', '0001_initial'),
        ('traders', '0003_alter_traderposition_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('candle_source', 'strategy', 'risk_manager', 'initial_balance'), name='unique_trader_constraint'),
        ),
    ]
