# Generated by Django 5.2.1 on 2025-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0003_remove_trader_max_position_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='max_positions_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное количество позиций'),
        ),
    ]
