# Generated by Django 5.2.1 on 2025-07-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0003_trader_errors'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='traderposition',
            constraint=models.UniqueConstraint(fields=('trader', 'opened_at', 'type', 'amount'), name='unique_position_constraint'),
        ),
    ]
