# Generated by Django 5.2.1 on 2025-07-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('risk_managers', '0001_initial'),
        ('strategies', '0001_initial'),
        ('traders', '0003_trader_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='candle_source',
            field=models.ForeignKey(help_text='Выберите источник свечей, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='exchanges.candlesource', verbose_name='Источник свечей'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='risk_manager',
            field=models.ForeignKey(help_text='Выберите риск-менеджер, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='risk_managers.riskmanager', verbose_name='Риск-менеджер'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='strategy',
            field=models.ForeignKey(help_text='Выберите стратегию, которую будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy', verbose_name='Стратегия'),
        ),
    ]
