# Generated by Django 5.2.1 on 2025-06-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('traders', '0003_trader_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traders', to='exchanges.candlesource'),
        ),
    ]
