# Generated by Django 5.2.6 on 2026-03-26 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0005_alter_exchangeclientorder_exchange_order_id'),
        ('traders', '0004_alter_tradererror_traceback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_order', to='exchange_clients.exchangeclientorder', verbose_name='Ордер биржи'),
        ),
    ]
