# Generated by Django 5.2.1 on 2025-06-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_alter_trader_max_positions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='max_positions_count',
        ),
    ]
