# Generated by Django 5.2.1 on 2025-09-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_remove_trader_unique_trader_trader_unique_trader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='close_posigion_by_strategy',
            new_name='close_position_by_strategy',
        ),
    ]
