# Generated by Django 5.2.6 on 2025-12-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_trader_use_fixed_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='use_fixed_balance',
            field=models.BooleanField(default=True, help_text='Если выбрано, трейдер будет использовать фиксированный баланс, игнорируя заработанные/проебанные деньги.', verbose_name='Использовать фиксированный баланс'),
        ),
    ]
