# Generated by Django 5.2.1 on 2025-06-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_traderorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraderHistory',
        ),
    ]
