# Generated by Django 5.2.1 on 2025-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_traderposition_unique_position_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderposition',
            old_name='updated_at',
            new_name='recalculated_at',
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='opened_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='tradersignal',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='Время'),
        ),
    ]
