# Generated by Django 5.2.6 on 2026-02-05 21:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0001_initial'),
        ('exchanges', '0001_initial'),
        ('traders', '0004_use_arbitrage_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetrader',
            name='first_exchange_client',
            field=models.ForeignKey(help_text='Первый клиент биржи для арбитражного трейдера.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_first_traders', to='exchange_clients.exchangeclient', verbose_name='Первый клиент биржи'),
        ),
        migrations.AlterField(
            model_name='arbitragetrader',
            name='second_exchange_client',
            field=models.ForeignKey(help_text='Второй клиент биржи для арбитражного трейдера.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_second_traders', to='exchange_clients.exchangeclient', verbose_name='Второй клиент биржи'),
        ),
        migrations.AlterField(
            model_name='arbitragetrader',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('error', 'Error'), ('paused', 'Paused')], default='disabled', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ArbitrageTraderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Тип')),
                ('first_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Тип (первая биржа)')),
                ('second_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Тип (вторая биржа)')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество')),
                ('first_open_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена открытия (первая биржа)')),
                ('first_close_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена закрытия (первая биржа)')),
                ('second_open_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена открытия (вторая биржа)')),
                ('second_close_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена закрытия (вторая биржа)')),
                ('opened_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время открытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('close_reason', models.CharField(blank=True, choices=[('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('opposite_signal', 'Opposite Signal'), ('strategy', 'Strategy'), ('timeout', 'Timeout'), ('manual', 'Manual')], help_text='Причина закрытия позиции, если она была закрыта.', max_length=20, null=True, verbose_name='Причина закрытия')),
                ('total_fee', models.DecimalField(decimal_places=18, default=Decimal('0.00'), max_digits=30, verbose_name='Общая комиссия')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='traders.arbitragetrader', verbose_name='Арбитражный трейдер')),
            ],
            options={
                'verbose_name': 'Позиция арбитражного трейдера',
                'verbose_name_plural': 'Позиции арбитражного трейдера',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('first_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_first_orders', to='exchange_clients.exchangeclientorder', verbose_name='Первый ордер')),
                ('second_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_second_orders', to='exchange_clients.exchangeclientorder', verbose_name='Второй ордер')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='traders.arbitragetrader', verbose_name='Арбитражный трейдер')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.arbitragetraderposition', verbose_name='Позиция трейдера')),
            ],
            options={
                'verbose_name': 'Ордер арбитражного трейдера',
                'verbose_name_plural': 'Ордера арбитражного трейдера',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Время')),
                ('first_price', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена (первая биржа)')),
                ('second_price', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена (вторая биржа)')),
                ('first_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('wait', 'Wait')], max_length=10, verbose_name='Тип (первая биржа)')),
                ('second_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('wait', 'Wait')], max_length=10, verbose_name='Тип (вторая биржа)')),
                ('data', models.JSONField()),
                ('first_candle', models.ForeignKey(blank=True, help_text='Первая свеча сигнала', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_first_signals', to='exchanges.exchangecandle', verbose_name='Первая свеча')),
                ('second_candle', models.ForeignKey(blank=True, help_text='Вторая свеча для арбитражного сигнала', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_second_signals', to='exchanges.exchangecandle', verbose_name='Вторая свеча')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='traders.arbitragetrader', verbose_name='Арбитражный трейдер')),
            ],
            options={
                'verbose_name': 'Сигнал арбитражного трейдера',
                'verbose_name_plural': 'Сигналы арбитражного трейдера',
            },
        ),
        migrations.AddIndex(
            model_name='arbitragetraderposition',
            index=models.Index(fields=['trader', 'status', 'opened_at'], name='arb_trader_pos_status_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitragetraderposition',
            index=models.Index(fields=['trader', 'status', 'closed_at'], name='arb_trader_pos_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitragetraderposition',
            index=models.Index(fields=['trader', 'type', 'status'], name='arb_trader_pos_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='arbitragetraderposition',
            constraint=models.UniqueConstraint(fields=('trader', 'opened_at', 'type', 'amount'), name='unique_arbitrage_position'),
        ),
        migrations.AddConstraint(
            model_name='arbitragetraderorder',
            constraint=models.UniqueConstraint(fields=('trader', 'first_order', 'second_order', 'position'), name='unique_arbitrage_trader_order'),
        ),
        migrations.AddIndex(
            model_name='arbitragetradersignal',
            index=models.Index(fields=['trader', '-timestamp'], name='arb_trader_signal_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitragetradersignal',
            index=models.Index(fields=['first_candle', 'second_candle'], name='arb_trader_signal_candles_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitragetradersignal',
            index=models.Index(fields=['trader', 'first_type', '-timestamp'], name='arb_trader_signal_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='arbitragetradersignal',
            constraint=models.UniqueConstraint(fields=('trader', 'timestamp', 'first_type', 'second_type'), name='unique_arb_trader_signal'),
        ),
    ]
