# Generated by Django 5.2.1 on 2025-07-04 18:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_alter_trader_candle_source_alter_trader_risk_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='max_drawdown_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Максимальная допустимая просадка в процентах от начального баланса.', max_digits=5, verbose_name='Макс. просадка (%)'),
        ),
        migrations.AddField(
            model_name='trader',
            name='max_positions_count',
            field=models.PositiveIntegerField(default=1, help_text='Максимальное количество одновременно открытых позиций.', verbose_name='Макс. количество позиций'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Внутренние данные трейдера, которые могут использоваться стратегией или риск-менеджером для принятия решений.', verbose_name='Внутренние данные'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='last_reboot',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего перезапуска трейдера. Используется для отслеживания активности трейдера.', null=True, verbose_name='Последний перезапуск'),
        ),
    ]
