# Generated by Django 5.2.1 on 2025-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_trader_unique_trader_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='last_reboot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний перезапуск'),
        ),
    ]
