# Generated by Django 5.2.1 on 2025-06-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0004_alter_trader_candle_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='traders.trader')),
            ],
            options={
                'verbose_name': 'История ордера',
                'verbose_name_plural': 'История ордеров',
            },
        ),
    ]
