# Generated by Django 5.2.6 on 2026-03-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0005_alter_traderorder_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderposition',
            name='unique_position',
        ),
        migrations.AddConstraint(
            model_name='traderposition',
            constraint=models.UniqueConstraint(fields=('trader', 'opened_at', 'amount', 'type'), name='unique_position'),
        ),
    ]
