# Generated by Django 5.2.1 on 2025-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_rename_value_tradingpair_symbol'),
        ('traders', '0005_rename_updated_at_traderposition_recalculated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='traderorder',
            constraint=models.UniqueConstraint(fields=('trader', 'order'), name='unique_trader_order_constraint'),
        ),
    ]
