# Generated by Django 5.2.6 on 2025-12-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('traders', '0005_alter_trader_use_fixed_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradersignal',
            name='candles',
            field=models.ManyToManyField(help_text='Свечи, на которых был сгенерирован сигнал.', to='exchanges.candle', verbose_name='Свечи'),
        ),
        migrations.CreateModel(
            name='ArbitrageTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('first_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_first_trader', to='traders.trader', verbose_name='Первый трейдер')),
                ('second_trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_second_trader', to='traders.trader', verbose_name='Второй трейдер')),
            ],
            options={
                'verbose_name': 'Арбитражный трейдер',
                'verbose_name_plural': 'Арбитражные трейдеры',
                'constraints': [models.UniqueConstraint(fields=('first_trader', 'second_trader'), name='unique_arbitrage_trader')],
            },
        ),
    ]
