# Generated by Django 5.2.1 on 2025-07-05 13:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0005_trader_max_drawdown_pct_trader_max_positions_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='max_drawdown_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Максимальная допустимая просадка в процентах от начального баланса.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Макс. просадка (%)'),
        ),
    ]
