# Generated by Django 5.2.1 on 2025-06-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0005_trader_last_reboot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='status',
            field=models.CharField(choices=[('TRADING', 'Trading'), ('REBOOTING', 'Rebooting')], default='TRADING'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='entry_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
