# Generated by Django 5.2.1 on 2025-06-08 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0005_delete_traderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='datasets')),
            ],
        ),
        migrations.CreateModel(
            name='TraderSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('wait', 'Wait')], default='wait', max_length=10)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='signals')),
            ],
        ),
    ]
