# Generated by Django 5.2.1 on 2025-09-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0004_alter_exchangeclientorder_amount'),
        ('exchanges', '0001_initial'),
        ('risk_managers', '0001_initial'),
        ('strategies', '0001_initial'),
        ('traders', '0005_rename_close_posigion_by_strategy_trader_close_position_by_strategy'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trader',
            name='unique_trader',
        ),
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timeframe', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled'), name='unique_trader'),
        ),
    ]
