# Generated by Django 5.2.6 on 2026-03-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0005_alter_candlesourceerror_type'),
        ('exchanges', '0021_alter_exchangetradingpair_max_leverage'),
        ('traders', '0006_remove_traderposition_unique_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderoptimizer',
            name='unique_trader_optimizer',
        ),
        migrations.AddConstraint(
            model_name='traderoptimizer',
            constraint=models.UniqueConstraint(fields=('algorithm', 'candle_source', 'strategy_class_name', 'risk_manager_class_name', 'initial_balance', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled', 'roi_weight', 'r2_weight', 'sharpe_weight', 'win_rate_weight'), name='unique_trader_optimizer'),
        ),
    ]
