# Generated by Django 5.2.1 on 2025-07-05 15:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0006_alter_trader_max_drawdown_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Начальный баланс'),
        ),
    ]
