# Generated by Django 5.2.1 on 2025-09-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0006_remove_trader_unique_trader_trader_unique_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderorder',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.traderposition', verbose_name='Позиция трейдера'),
        ),
    ]
