# Generated by Django 5.2.6 on 2025-12-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('traders', '0006_tradersignal_candles_arbitragetrader'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradersignal',
            name='unique_signal',
        ),
        migrations.RemoveField(
            model_name='tradersignal',
            name='price',
        ),
        migrations.AddConstraint(
            model_name='tradersignal',
            constraint=models.UniqueConstraint(fields=('trader', 'timestamp', 'type'), name='unique_signal'),
        ),
    ]
