# Generated by Django 5.2.1 on 2025-07-31 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0007_tradingpair_min_amount'),
        ('traders', '0006_traderorder_unique_trader_order_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='data',
        ),
        migrations.AddField(
            model_name='trader',
            name='last_error',
            field=models.DateTimeField(blank=True, help_text='Дата и время последней ошибки трейдера. ', null=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AddField(
            model_name='tradersignal',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TraderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.candle')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.tradersignal')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader')),
            ],
            options={
                'verbose_name': 'История состояний трейдера',
                'verbose_name_plural': 'История состояний трейдеров',
                'constraints': [models.UniqueConstraint(fields=('trader', 'timestamp'), name='unique_trader_state_constraint')],
            },
        ),
    ]
