# Generated by Django 5.2.1 on 2025-06-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0006_trader_status_alter_traderposition_entry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='status',
            field=models.CharField(choices=[('trading', 'Trading'), ('rebooting', 'Rebooting')], default='trading'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='type',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10),
        ),
    ]
