# Generated by Django 5.2.1 on 2025-06-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0006_traderdata_tradersignal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='strategy_data',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='traderdata',
            name='trader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traders.trader'),
        ),
        migrations.DeleteModel(
            name='TraderOrder',
        ),
    ]
