# Generated by Django 5.2.6 on 2026-03-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0007_remove_traderoptimizer_unique_trader_optimizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderoptimizer',
            name='exchange',
        ),
    ]
