# Generated by Django 5.2.1 on 2025-06-08 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0009_remove_exchangeorder_unique_exchange_client_and_timestamp_and_exchange_order_id_and_more'),
        ('traders', '0007_rename_strategy_data_trader_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangeorder')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader')),
            ],
            options={
                'verbose_name': 'Ордер трейдера',
                'verbose_name_plural': 'Ордера трейдера',
            },
        ),
    ]
