# Generated by Django 5.2.1 on 2025-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0007_remove_trader_data_trader_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderposition',
            name='close_reason',
            field=models.CharField(choices=[('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('opposite_signal', 'Opposite Signal'), ('strategy', 'Strategy'), ('timeout', 'Timeout'), ('manual', 'Manual')], default='manual', help_text='Причина закрытия позиции, если она была закрыта.', max_length=20, verbose_name='Причина закрытия'),
            preserve_default=False,
        ),
    ]
