# Generated by Django 5.2.1 on 2025-07-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0007_traderposition_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderposition',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Время последнего обновления позиции. Используется для отслеживания изменений в позиции.', null=True, verbose_name='Время обновления'),
        ),
    ]
