# Generated by Django 5.2.1 on 2025-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0007_alter_trader_status_alter_traderposition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting')], default='disabled'),
        ),
    ]
