# Generated by Django 5.2.1 on 2025-09-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0005_exchangeclientcandlesource_errors'),
        ('traders', '0007_alter_traderorder_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderorder',
            name='unique_trader_order',
        ),
        migrations.AddConstraint(
            model_name='traderorder',
            constraint=models.UniqueConstraint(fields=('trader', 'order', 'position'), name='unique_trader_order'),
        ),
    ]
