# Generated by Django 5.2.6 on 2025-12-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0007_remove_tradersignal_unique_signal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradersignal',
            name='price',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
