# Generated by Django 5.2.1 on 2025-06-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0008_traderorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraderData',
        ),
    ]
