# Generated by Django 5.2.1 on 2025-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0008_alter_traderposition_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='trail_stop_enabled',
            field=models.BooleanField(default=False, help_text='Если выбрано, трейдер будет использовать трейлинг-стоп для позиций.', verbose_name='Трейлинг-стоп включен'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Время последнего обновления позиции. Используется для отслеживания изменений в позиции.', null=True, verbose_name='Время последнего обновления'),
        ),
    ]
