# Generated by Django 5.2.1 on 2025-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0008_traderposition_close_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderposition',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
