# Generated by Django 5.2.6 on 2026-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0005_alter_candlesourceerror_type'),
        ('traders', '0008_remove_traderoptimizer_exchange'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderoptimizer',
            name='unique_trader_optimizer',
        ),
        migrations.AddField(
            model_name='traderoptimizer',
            name='lookback_period',
            field=models.CharField(choices=[('1w', '1 неделя'), ('2w', '2 недели'), ('1M', '1 месяц'), ('3M', '3 месяца'), ('6M', '6 месяцев'), ('1y', '1 год'), ('2y', '2 года'), ('3y', '3 года')], default='1y', max_length=5, verbose_name='Период оптимизации'),
        ),
        migrations.AddConstraint(
            model_name='traderoptimizer',
            constraint=models.UniqueConstraint(fields=('algorithm', 'candle_source', 'strategy_class_name', 'risk_manager_class_name', 'initial_balance', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled', 'lookback_period', 'roi_weight', 'r2_weight', 'sharpe_weight', 'win_rate_weight'), name='unique_trader_optimizer'),
        ),
    ]
