# Generated by Django 5.2.1 on 2025-09-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0008_remove_traderorder_unique_trader_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderposition',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество'),
        ),
    ]
