# Generated by Django 5.2.6 on 2026-04-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0009_remove_traderoptimizer_unique_trader_optimizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderoptimizer',
            name='lookback_period',
            field=models.CharField(choices=[('1w', '1 неделя'), ('2w', '2 недели'), ('1M', '1 месяц'), ('3M', '3 месяца'), ('6M', '6 месяцев'), ('1y', '1 год'), ('2y', '2 года'), ('3y', '3 года')], default='1w', max_length=5, verbose_name='Период оптимизации'),
        ),
    ]
