# Generated by Django 5.2.1 on 2025-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0009_trader_trail_stop_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='trail_stop_enabled',
            field=models.BooleanField(default=False, help_text='Если выбрано, трейдер будет использовать трейлинг-стоп для позиций.', verbose_name='Трейлинг-стоп'),
        ),
    ]
