# Generated by Django 5.2.1 on 2025-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0009_alter_traderposition_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='traderorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='traderorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='traderposition',
            name='recalculated_at',
            field=models.DateTimeField(blank=True, help_text='Время последнего обновления значений в позиции.', null=True, verbose_name='Время последнего перерасчета'),
        ),
    ]
