# Generated by Django 5.2.1 on 2025-06-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0009_delete_traderdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraderSignal',
        ),
    ]
