# Generated by Django 5.2.1 on 2025-08-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0010_alter_traderposition_close_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderposition',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('opposite_signal', 'Opposite Signal'), ('strategy', 'Strategy'), ('timeout', 'Timeout'), ('manual', 'Manual')], help_text='Причина закрытия позиции, если она была закрыта.', max_length=20, null=True, verbose_name='Причина закрытия'),
        ),
    ]
