# Generated by Django 5.2.1 on 2025-06-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0010_delete_tradersignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('wait', 'Wait')], max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader')),
            ],
        ),
    ]
