# Generated by Django 5.2.6 on 2025-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0010_alter_trader_created_at_alter_trader_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='create_new_orders',
            field=models.BooleanField(default=True, help_text='Если выбрано, трейдер будет создавать новые ордера согласно своей стратегии.', verbose_name='Создавать ордера биржи'),
        ),
    ]
