# Generated by Django 5.2.1 on 2025-08-01 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0001_initial'),
        ('traders', '0011_alter_traderposition_close_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='exchange_client',
            field=models.ForeignKey(help_text='Выберите клиента биржи, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи'),
        ),
        migrations.AlterField(
            model_name='traderorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeorder', verbose_name='Ордер биржи'),
        ),
    ]
