# Generated by Django 5.2.6 on 2026-04-08 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0011_alter_trader_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderoptimizererror',
            name='optimizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='traders.traderoptimizer', verbose_name='Оптимизатор'),
        ),
    ]
