# Generated by Django 5.2.6 on 2025-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0011_trader_create_new_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='trail_stop_enabled',
            field=models.BooleanField(default=True, help_text='Если выбрано, трейдер будет использовать трейлинг-стоп для позиций.', verbose_name='Трейлинг-стоп'),
        ),
    ]
