# Generated by Django 5.2.1 on 2025-07-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_alter_exchange_class_name'),
        ('risk_managers', '0001_initial'),
        ('strategies', '0001_initial'),
        ('traders', '0011_trader_exchange_client_trader_timeframe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trader',
            name='unique_trader_constraint',
        ),
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timeframe', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count'), name='unique_trader_constraint'),
        ),
    ]
