# Generated by Django 5.2.1 on 2025-07-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0010_candle_unique_candle'),
        ('risk_managers', '0001_initial'),
        ('strategies', '0001_initial'),
        ('traders', '0012_remove_trader_unique_trader_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trader',
            name='unique_trader_constraint',
        ),
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timeframe', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'trail_stop_enabled'), name='unique_trader_constraint'),
        ),
    ]
