# Generated by Django 5.2.6 on 2026-04-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0012_remove_candlesource_is_active_candlesource_status'),
        ('traders', '0012_alter_traderoptimizererror_optimizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candle_sources.candlesource', verbose_name='Источник свечей'),
        ),
        migrations.AlterField(
            model_name='traderoptimizer',
            name='candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candle_sources.candlesource', verbose_name='Источник свечей'),
        ),
    ]
