# Generated by Django 5.2.1 on 2025-07-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0013_remove_trader_unique_trader_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='candle_source',
        ),
    ]
