# Generated by Django 5.2.6 on 2026-04-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0013_alter_trader_candle_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderposition',
            name='close_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Кол-во закрытия'),
        ),
        migrations.AddField(
            model_name='traderposition',
            name='open_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Кол-во открытия'),
        ),
    ]
