# Generated by Django 5.2.6 on 2025-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0013_traderposition_created_at_traderposition_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='last_reboot',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего перезапуска трейдера.', null=True, verbose_name='Последний перезапуск'),
        ),
    ]
