# Generated by Django 5.2.6 on 2026-04-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0014_traderposition_close_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderposition',
            name='close_cost',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Стоимость закрытия'),
        ),
        migrations.AddField(
            model_name='traderposition',
            name='open_cost',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Стоимость открытия'),
        ),
    ]
