# Generated by Django 5.2.6 on 2025-10-25 14:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0014_alter_trader_last_reboot'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderposition',
            name='total_fee',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.00'), max_digits=30, verbose_name='Общая комиссия'),
        ),
    ]
