# Generated by Django 5.2.6 on 2025-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0015_traderposition_total_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='max_positions_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Максимальное количество одновременно открытых позиций.', verbose_name='Макс. количество позиций'),
        ),
    ]
