# Generated by Django 5.2.6 on 2026-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0015_traderposition_close_cost_traderposition_open_cost'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traderposition',
            name='unique_position',
        ),
        migrations.RemoveField(
            model_name='traderposition',
            name='amount',
        ),
        migrations.AddConstraint(
            model_name='traderposition',
            constraint=models.UniqueConstraint(fields=('trader', 'opened_at', 'type'), name='unique_position'),
        ),
    ]
