# Generated by Django 5.2.6 on 2025-10-25 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0016_alter_trader_max_positions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='max_positions_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Максимальное количество одновременно открытых позиций.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Макс. количество позиций'),
        ),
    ]
