# Generated by Django 5.2.6 on 2025-11-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0017_alter_trader_max_positions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('error', 'Error'), ('paused', 'Paused')], default='disabled', verbose_name='Статус'),
        ),
    ]
