# Generated by Django 5.2.6 on 2025-12-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0018_alter_trader_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='check_drawdown',
            field=models.BooleanField(default=True, help_text='Если выбрано, трейдер будет проверять максимальную просадку.', verbose_name='Проверять просадку'),
        ),
    ]
