# Generated by Django 5.2.6 on 2025-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0019_trader_check_drawdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderposition',
            name='data',
        ),
    ]
