# Generated by Django 5.2.6 on 2025-12-07 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0014_exchangeclientorder_cost_and_more'),
        ('exchanges', '0005_tradingpair_fee_percent_tradingpair_max_amount_and_more'),
        ('risk_managers', '0004_alter_riskmanager_name'),
        ('strategies', '0004_alter_strategy_name'),
        ('traders', '0020_remove_traderposition_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trader',
            name='unique_trader',
        ),
        migrations.AddField(
            model_name='trader',
            name='candle_source',
            field=models.ForeignKey(default=1, help_text='Выберите источник свечей, который будет использовать трейдер.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclientcandlesource', verbose_name='Источник свечей'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'candle_source', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'close_position_by_stop_loss', 'close_position_by_take_profit', 'trail_stop_enabled'), name='unique_trader'),
        ),
    ]
