# Generated by Django 5.2.6 on 2025-12-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0021_remove_trader_unique_trader_trader_candle_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='timeframe',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='trading_pair',
        ),
    ]
