# Generated by Django 5.2.1 on 2025-06-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candle',
            name='unique_exchange_timestamp',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='timeframe',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='trading_pair',
        ),
    ]
