# Generated by Django 5.2.1 on 2025-06-27 22:45

import backend.risk_managers.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(choices=backend.risk_managers.domain.base.RiskManagerRegistry.get_choices, max_length=100)),
                ('arguments', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Риск-менеджер',
                'verbose_name_plural': 'Риск-менеджеры',
            },
        ),
    ]
