# Generated by Django 5.2.1 on 2025-06-30 22:54

import risk_managers.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanager',
            name='arguments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)'),
        ),
        migrations.AlterField(
            model_name='riskmanager',
            name='class_name',
            field=models.CharField(choices=risk_managers.domain.base.RiskManagerRegistry.get_choices, max_length=100, verbose_name='Класс риск-менеджера'),
        ),
        migrations.AlterField(
            model_name='riskmanager',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название риск-менеджера'),
        ),
    ]
