# Generated by Django 5.2.1 on 2025-06-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskmanager',
            options={'verbose_name': 'Риск-менеджер', 'verbose_name_plural': 'Риск-менеджеры'},
        ),
    ]
