# Generated by Django 5.2.1 on 2025-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_managers', '0002_alter_riskmanager_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanager',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
