# Generated by Django 5.2.6 on 2025-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_managers', '0003_alter_riskmanager_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanager',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название риск-менеджера'),
        ),
    ]
