# Generated by Django 5.2.1 on 2025-06-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0002_exchange_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3)),
                ('timestamp', models.DateTimeField(verbose_name='Временная метка')),
                ('high', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Максимальная цена за период свечи')),
                ('low', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Минимальная цена за период свечи')),
                ('open', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена открытия свечи')),
                ('close', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена закрытия свечи')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Объём за период свечи')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exchange', 'timestamp'), name='unique_exchange_timestamp')],
            },
        ),
    ]
