# Generated by Django 5.2.6 on 2025-12-21 16:31

import candle_sources.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('class_name', models.CharField(choices=candle_sources.domain.base.CandleSourceRegistry.get_choices, max_length=100, verbose_name='Класс стратегии')),
                ('exchange_client_candle_sources', models.ManyToManyField(to='exchange_clients.exchangeclientcandlesource')),
            ],
            options={
                'verbose_name': 'Источник свечей',
                'verbose_name_plural': 'Источники свечей',
            },
        ),
    ]
