# Generated by Django 5.2.6 on 2026-05-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3, verbose_name='Таймфрейм')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('syncing', 'Syncing'), ('clearing', 'Clearing'), ('error', 'Error')], default='enabled', max_length=10, verbose_name='Статус')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle_sources', to='exchanges.exchangetradingpair', verbose_name='Торговая пара биржи')),
            ],
            options={
                'verbose_name': 'Источник свечей',
                'verbose_name_plural': 'Источники свечей',
            },
        ),
        migrations.CreateModel(
            name='CandleSourceError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('type', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип ошибки')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='Traceback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('candle_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='candle_sources.candlesource', verbose_name='Источник свечей')),
            ],
            options={
                'verbose_name': 'Ошибка источника свечей',
                'verbose_name_plural': 'Ошибки источников свечей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='candlesource',
            constraint=models.UniqueConstraint(fields=('trading_pair', 'timeframe'), name='unique_candle_source_exchange'),
        ),
    ]
