# Generated by Django 5.2.6 on 2025-12-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candle_sources', '0001_initial'),
        ('exchange_clients', '0001_initial'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlesource',
            name='exchange_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи'),
        ),
        migrations.AddField(
            model_name='candlesource',
            name='trading_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара'),
        ),
        migrations.AddConstraint(
            model_name='candlesource',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timeframe'), name='unique_candle_source'),
        ),
    ]
