# Generated by Django 5.2.6 on 2026-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlesource',
            name='errors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='candlesourceerror',
            name='traceback',
            field=models.TextField(blank=True, default='', verbose_name='Traceback'),
        ),
    ]
