# Generated by Django 5.2.6 on 2026-03-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlesource',
            name='mode',
            field=models.CharField(choices=[('rest', 'REST'), ('ws', 'WebSocket')], default='rest', max_length=4, verbose_name='Режим получения данных'),
        ),
    ]
