# Generated by Django 5.2.6 on 2025-12-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlesource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
