# Generated by Django 5.2.6 on 2026-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0004_alter_candlesource_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlesourceerror',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тип ошибки'),
        ),
    ]
