# Generated by Django 5.2.6 on 2026-03-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0005_alter_candlesourceerror_type'),
        ('exchange_clients', '0005_alter_exchangeclientorder_exchange_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlesource',
            name='exchange_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle_sources', to='exchange_clients.exchangeclient', verbose_name='Клиент биржи'),
        ),
    ]
