# Generated by Django 5.2.6 on 2026-04-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0006_alter_candlesource_exchange_client'),
        ('exchanges', '0024_add_min_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlesource',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candle_sources', to='exchanges.exchange', verbose_name='Биржа'),
        ),
    ]
