# Generated by Django 5.2.6 on 2026-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0008_populate_exchange_fk'),
        ('exchange_clients', '0005_alter_exchangeclientorder_exchange_order_id'),
        ('exchanges', '0024_add_min_leverage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candlesource',
            name='unique_candle_source',
        ),
        migrations.AddConstraint(
            model_name='candlesource',
            constraint=models.UniqueConstraint(fields=('exchange', 'trading_pair', 'timeframe'), name='unique_candle_source_exchange'),
        ),
    ]
