# Generated by Django 5.2.6 on 2026-04-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0010_remove_exchange_client_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candlesource',
            name='mode',
        ),
    ]
