# Generated by Django 5.2.6 on 2026-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0011_remove_candlesource_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candlesource',
            name='is_active',
        ),
        migrations.AddField(
            model_name='candlesource',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('syncing', 'Syncing'), ('clearing', 'Clearing'), ('error', 'Error')], default='enabled', max_length=10, verbose_name='Статус'),
        ),
    ]
