# Generated by Django 5.2.6 on 2026-05-01 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candle_sources', '0012_remove_candlesource_is_active_candlesource_status'),
        ('exchanges', '0033_add_trading_pair_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='candlesource',
            name='trading_pair_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exchanges.exchangetradingpair', verbose_name='Торговая пара биржи (новая FK)'),
        ),
    ]
