# Generated by Django 5.2.6 on 2025-12-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeClientProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('protocol', models.CharField(choices=[('socks5', 'Socks5'), ('socks4', 'Socks4')], default='socks5', max_length=10, verbose_name='Протокол')),
                ('host', models.CharField(max_length=100, unique=True, verbose_name='Хост')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Ошибки')),
            ],
            options={
                'verbose_name': 'Прокси сервер',
                'verbose_name_plural': 'Прокси серверы',
            },
        ),
        migrations.CreateModel(
            name='ExchangeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=20, verbose_name='Название клиента')),
                ('api_key', models.CharField(max_length=200, verbose_name='API ключ')),
                ('api_secret', models.CharField(max_length=200, verbose_name='API секрет')),
                ('demo', models.BooleanField(default=True, verbose_name='Демо режим')),
                ('exchange', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclientproxy', verbose_name='Прокси')),
            ],
            options={
                'verbose_name': 'Клиент Биржи',
                'verbose_name_plural': 'Клиенты Бирж',
            },
        ),
        migrations.CreateModel(
            name='ExchangeClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('debt', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Долг')),
                ('free', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Свободно')),
                ('used', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Использовано')),
                ('total', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Всего')),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
            ],
            options={
                'verbose_name': 'Баланс Клиента Биржи',
                'verbose_name_plural': 'Балансы Клиентов Бирж',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'currency'), name='unique_balance')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeClientCandleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3, verbose_name='Таймфрейм')),
                ('errors', models.TextField(blank=True, null=True)),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Источник свечей',
                'verbose_name_plural': 'Источники свечей',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timeframe'), name='unique_candle_source')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_order_id', models.CharField(db_index=True, max_length=50, verbose_name='ID ордера на бирже')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='opened', max_length=10, verbose_name='Статус ордера')),
                ('type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], default='market', max_length=10, verbose_name='Тип ордера')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, verbose_name='Сторона (BUY/SELL)')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Время ордера')),
                ('price', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Стоимость')),
                ('fee', models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Комиссия')),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Ордер Клиента',
                'verbose_name_plural': 'Ордер Клиента',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timestamp', 'exchange_order_id'), name='unique_exchange_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangeclient',
            constraint=models.UniqueConstraint(fields=('api_key', 'api_secret'), name='unique_exchange_client'),
        ),
    ]
