# Generated by Django 5.2.6 on 2026-02-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeClientProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('protocol', models.CharField(choices=[('socks5', 'Socks5'), ('socks4', 'Socks4')], default='socks5', max_length=10, verbose_name='Протокол')),
                ('host', models.CharField(max_length=100, unique=True, verbose_name='Хост')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('errors', models.TextField(blank=True, default='', verbose_name='Ошибки')),
            ],
            options={
                'verbose_name': 'Прокси сервер',
                'verbose_name_plural': 'Прокси серверы',
            },
        ),
        migrations.CreateModel(
            name='ExchangeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('api_key', models.CharField(max_length=200, verbose_name='API ключ')),
                ('api_secret', models.CharField(max_length=200, verbose_name='API секрет')),
                ('demo', models.BooleanField(default=True, verbose_name='Демо-режим')),
                ('exchange', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclientproxy', verbose_name='Прокси')),
            ],
            options={
                'verbose_name': 'Клиент биржи',
                'verbose_name_plural': 'Клиенты бирж',
            },
        ),
        migrations.CreateModel(
            name='ExchangeClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('debt', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Долг')),
                ('free', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Свободный баланс')),
                ('used', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Использованный баланс')),
                ('total', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Общий баланс')),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
            ],
            options={
                'verbose_name': 'Баланс клиента',
                'verbose_name_plural': 'Балансы клиентов',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'currency'), name='unique_balance')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_order_id', models.CharField(max_length=50, verbose_name='ID ордера')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='opened', max_length=10, verbose_name='Статус ордера')),
                ('type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], default='market', max_length=10, verbose_name='Тип ордера')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, verbose_name='Сторона ордера')),
                ('timestamp', models.DateTimeField(verbose_name='Время исполнения')),
                ('price', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена исполнения')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество актива')),
                ('cost', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Стоимость ордера')),
                ('fee', models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Комиссия за ордер')),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Ордер Клиента',
                'verbose_name_plural': 'Ордера клиента',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timestamp', 'exchange_order_id'), name='unique_exchange_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangeclient',
            constraint=models.UniqueConstraint(fields=('api_key', 'api_secret'), name='unique_exchange_client'),
        ),
    ]
