# Generated by Django 5.2.1 on 2025-08-01 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0007_tradingpair_min_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('socks5', 'Socks5'), ('socks4', 'Socks4')], default='socks5', max_length=10, verbose_name='Протокол')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Ошибки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Название клиента')),
                ('api_key', models.CharField(max_length=200, verbose_name='API ключ')),
                ('api_secret', models.CharField(max_length=200, verbose_name='API секрет')),
                ('demo', models.BooleanField(default=True, verbose_name='Демо режим')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange', verbose_name='Биржа')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.proxy', verbose_name='Прокси')),
            ],
            options={
                'verbose_name': 'Клиент Биржи',
                'verbose_name_plural': 'Клиенты Бирж',
            },
        ),
        migrations.CreateModel(
            name='CandleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3, verbose_name='Таймфрейм')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
            ],
            options={
                'verbose_name': 'Источник свечей',
                'verbose_name_plural': 'Источники свечей',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timeframe'), name='unique_candle_source_constraint')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeClientBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество')),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
            ],
            options={
                'verbose_name': 'Баланс Клиента Биржи',
                'verbose_name_plural': 'Балансы Клиентов Бирж',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'currency'), name='unique_balance')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_order_id', models.CharField(db_index=True, max_length=50, verbose_name='ID ордера на бирже')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='opened', max_length=10, verbose_name='Статус ордера')),
                ('type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop')], default='market', max_length=10, verbose_name='Тип ордера')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, verbose_name='Сторона (BUY/SELL)')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Время ордера')),
                ('price', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Объем')),
                ('fee', models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Комиссия')),
                ('exchange_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_clients.exchangeclient', verbose_name='Клиент биржи')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Ордер биржи',
                'verbose_name_plural': 'Ордера биржи',
                'constraints': [models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'timestamp', 'exchange_order_id'), name='unique_exchange_order_constraint')],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangeclient',
            constraint=models.UniqueConstraint(fields=('api_key', 'api_secret'), name='unique_exchange_client'),
        ),
    ]
