# Generated by Django 5.2.6 on 2026-02-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeclientbalance',
            name='exchange_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='exchange_clients.exchangeclient', verbose_name='Клиент биржи'),
        ),
        migrations.AlterField(
            model_name='exchangeclientorder',
            name='exchange_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchange_clients.exchangeclient', verbose_name='Клиент биржи'),
        ),
    ]
