# Generated by Django 5.2.6 on 2026-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeclientbalance',
            name='market_type',
            field=models.CharField(choices=[('futures', 'Futures'), ('spot', 'Spot'), ('index', 'Index')], max_length=10, verbose_name='Тип рынка'),
        ),
    ]
