# Generated by Django 5.2.6 on 2026-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeclientproxy',
            name='errors',
            field=models.TextField(blank=True, default='', verbose_name='Ошибки'),
        ),
    ]
