# Generated by Django 5.2.6 on 2026-02-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0001_initial'),
        ('exchanges', '0002_populate_exchanges_and_pairs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangeclientorder',
            name='unique_exchange_order',
        ),
        migrations.AddConstraint(
            model_name='exchangeclientorder',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'trading_pair', 'exchange_order_id', 'timestamp'), name='unique_exchange_order'),
        ),
    ]
