# Generated by Django 5.2.1 on 2025-08-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0002_alter_exchangeclient_exchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeclientorder',
            options={'verbose_name': 'Ордер Клиента', 'verbose_name_plural': 'Ордер Клиента'},
        ),
    ]
