# Generated by Django 5.2.6 on 2026-02-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0002_remove_exchangeclientorder_unique_exchange_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeclient',
            name='api_password',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='API пароль (passphrase)'),
        ),
    ]
