# Generated by Django 5.2.6 on 2026-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0003_add_api_password_to_exchange_client'),
        ('exchanges', '0007_alter_tradingpair_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangeclient',
            name='unique_exchange_client',
        ),
        migrations.RemoveField(
            model_name='exchangeclient',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='exchangeclient',
            name='api_password',
        ),
        migrations.RemoveField(
            model_name='exchangeclient',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='exchangeclient',
            name='demo',
        ),
        migrations.AddField(
            model_name='exchangeclient',
            name='arguments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)'),
        ),
        migrations.AddConstraint(
            model_name='exchangeclient',
            constraint=models.UniqueConstraint(fields=('exchange', 'name'), name='unique_exchange_client'),
        ),
    ]
