# Generated by Django 5.2.1 on 2025-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0003_alter_exchangeclientorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeclientorder',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Кол-во'),
        ),
    ]
