# Generated by Django 5.2.6 on 2026-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0004_remove_exchangeclient_unique_exchange_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeclientorder',
            name='exchange_order_id',
            field=models.CharField(max_length=255, verbose_name='ID ордера'),
        ),
    ]
