# Generated by Django 5.2.1 on 2025-09-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0004_alter_exchangeclientorder_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeclientcandlesource',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
