# Generated by Django 5.2.6 on 2026-04-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0005_alter_exchangeclientorder_exchange_order_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangeclientbalance',
            name='unique_balance',
        ),
        migrations.AddField(
            model_name='exchangeclientbalance',
            name='market_type',
            field=models.CharField(choices=[('futures', 'Futures'), ('spot', 'Spot')], default='futures', max_length=10, verbose_name='Тип рынка'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='exchangeclientbalance',
            constraint=models.UniqueConstraint(fields=('exchange_client', 'currency', 'market_type'), name='unique_balance'),
        ),
    ]
