# Generated by Django 5.2.6 on 2025-09-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0007_alter_exchangeclient_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='address',
            new_name='host',
        ),
    ]
