# Generated by Django 5.2.6 on 2025-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0008_rename_address_proxy_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='host',
            field=models.CharField(max_length=100, unique=True, verbose_name='Хост'),
        ),
    ]
