# Generated by Django 5.2.6 on 2025-09-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0009_alter_proxy_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeclientbalance',
            name='debt',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Долг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeclientbalance',
            name='free',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Свободно'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeclientbalance',
            name='total',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Всего'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangeclientbalance',
            name='used',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Использовано'),
            preserve_default=False,
        ),
    ]
