# Generated by Django 5.2.6 on 2025-09-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0010_exchangeclientbalance_debt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeclientbalance',
            name='amount',
        ),
    ]
