# Generated by Django 5.2.6 on 2025-09-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0011_remove_exchangeclientbalance_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proxy',
            new_name='ExchangeClientProxy',
        ),
    ]
