# Generated by Django 5.2.6 on 2025-09-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0012_rename_proxy_exchangeclientproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeclientproxy',
            options={'verbose_name': 'Прокси сервер', 'verbose_name_plural': 'Прокси серверы'},
        ),
    ]
