# Generated by Django 5.2.6 on 2025-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_clients', '0013_alter_exchangeclientproxy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeclientorder',
            name='cost',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=30, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangeclientorder',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество'),
        ),
    ]
