# Generated by Django 5.2.1 on 2025-06-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_exchange_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle_sources', to='exchanges.exchange')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle_sources', to='exchanges.tradingpair')),
            ],
            options={
                'verbose_name': 'Candle Source',
                'verbose_name_plural': 'Candle Sources',
                'constraints': [models.UniqueConstraint(fields=('exchange', 'trading_pair', 'timeframe'), name='unique_exchange_pair_timeframe')],
            },
        ),
    ]
