# Generated by Django 5.2.6 on 2026-02-16 18:03

import arbitrage_traders.domain.optimizations.base
import arbitrage_traders.domain.risk_managers.base
import arbitrage_traders.domain.strategies.base
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candle_sources', '0001_initial'),
        ('exchange_clients', '0001_initial'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOptimizationAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название алгоритма оптимизации')),
                ('class_name', models.CharField(choices=arbitrage_traders.domain.optimizations.base.ArbitrageOptimizerRegistry.get_choices, max_length=100, verbose_name='Класс алгоритма оптимизации')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)')),
            ],
            options={
                'verbose_name': 'Арбитражный алгоритм оптимизации',
                'verbose_name_plural': 'Арбитражные алгоритмы оптимизации',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageRiskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название арбитражного риск-менеджера')),
                ('class_name', models.CharField(choices=arbitrage_traders.domain.risk_managers.base.ArbitrageRiskManagerRegistry.get_choices, max_length=100, verbose_name='Класс арбитражного риск-менеджера')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)')),
            ],
            options={
                'verbose_name': 'Арбитражный риск-менеджер',
                'verbose_name_plural': 'Арбитражные риск-менеджеры',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название арбитражной стратегии')),
                ('class_name', models.CharField(choices=arbitrage_traders.domain.strategies.base.ArbitrageStrategyRegistry.get_choices, max_length=100, verbose_name='Класс арбитражной стратегии')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)')),
            ],
            options={
                'verbose_name': 'Арбитражная стратегия',
                'verbose_name_plural': 'Арбитражные стратегии',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранный')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('error', 'Error'), ('paused', 'Paused')], default='disabled', verbose_name='Статус')),
                ('use_fixed_balance', models.BooleanField(default=True, verbose_name='Фиксированный баланс')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Начальный баланс')),
                ('check_drawdown', models.BooleanField(default=True, verbose_name='Проверка просадки')),
                ('max_drawdown_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Макс. просадка (%)')),
                ('create_new_orders', models.BooleanField(default=True, verbose_name='Создавать ордера')),
                ('max_positions_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Макс. количество позиций')),
                ('close_position_by_opposite_signal', models.BooleanField(default=True, verbose_name='Закрытие по противоположному сигналу')),
                ('close_position_by_strategy', models.BooleanField(default=True, verbose_name='Закрытие по стратегии')),
                ('last_reboot', models.DateTimeField(blank=True, null=True, verbose_name='Последний перезапуск')),
                ('left_candle_source', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_left_traders', to='candle_sources.candlesource', verbose_name='Первый источник свечей')),
                ('left_exchange_client', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_left_traders', to='exchange_clients.exchangeclient', verbose_name='Первый клиент биржи')),
                ('right_candle_source', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_right_traders', to='candle_sources.candlesource', verbose_name='Второй источник свечей')),
                ('right_exchange_client', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_right_traders', to='exchange_clients.exchangeclient', verbose_name='Второй клиент биржи')),
                ('risk_manager', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='arbitrage_traders.arbitrageriskmanager', verbose_name='Риск-менеджер')),
                ('strategy', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='arbitrage_traders.arbitragestrategy', verbose_name='Стратегия')),
            ],
            options={
                'verbose_name': 'Арбитражный трейдер',
                'verbose_name_plural': 'Арбитражные трейдеры',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='Трассировка ошибки')),
                ('type', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип ошибки')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='arbitrage_traders.arbitragetrader', verbose_name='Арбитражный трейдер')),
            ],
            options={
                'verbose_name': 'Арбитражная ошибка трейдера',
                'verbose_name_plural': 'Арбитражные ошибки трейдера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderOptimizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('error', 'Error')], default='enabled', max_length=10, verbose_name='Статус оптимизатора')),
                ('strategy_class_name', models.CharField(choices=arbitrage_traders.domain.strategies.base.ArbitrageStrategyRegistry.get_choices, max_length=100, verbose_name='Класс стратегии')),
                ('risk_manager_class_name', models.CharField(choices=arbitrage_traders.domain.risk_managers.base.ArbitrageRiskManagerRegistry.get_choices, max_length=100, verbose_name='Класс риск-менеджера')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Начальный баланс')),
                ('max_positions_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Макс. количество позиций')),
                ('close_position_by_opposite_signal', models.BooleanField(default=True, verbose_name='Закрытие по противоположному сигналу')),
                ('close_position_by_strategy', models.BooleanField(default=True, verbose_name='Закрытие по стратегии')),
                ('roi_weight', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Вес ROI')),
                ('r2_weight', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Вес R²')),
                ('sharpe_weight', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Вес Sharpe')),
                ('win_rate_weight', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Вес Win Rate')),
                ('algorithm', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='arbitrage_traders.arbitrageoptimizationalgorithm', verbose_name='Алгоритм оптимизации')),
                ('left_candle_source', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_optimizer_left', to='candle_sources.candlesource', verbose_name='Первый источник свечей')),
                ('right_candle_source', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_optimizer_right', to='candle_sources.candlesource', verbose_name='Второй источник свечей')),
            ],
            options={
                'verbose_name': 'Арбитражный оптимизатор трейдера',
                'verbose_name_plural': 'Арбитражные оптимизаторы трейдеров',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderOptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('duration', models.DurationField(verbose_name='Длительность оптимизации')),
                ('pnl', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Теоретический PnL')),
                ('win_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Процент побед (Win Rate)')),
                ('avg_candles_per_position', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Среднее свечей на позицию')),
                ('pnl_r2', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='R² для PnL')),
                ('roi', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ROI')),
                ('sharpe', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Sharpe Ratio')),
                ('total_positions', models.PositiveIntegerField(verbose_name='Количество позиций')),
                ('strategy_arguments', models.JSONField(verbose_name='Параметры стратегии')),
                ('risk_manager_arguments', models.JSONField(verbose_name='Параметры риск-менеджера')),
                ('optimizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage_traders.arbitragetraderoptimizer', verbose_name='Конфигурация оптимизации')),
            ],
            options={
                'verbose_name': 'Результат оптимизации (арбитраж)',
                'verbose_name_plural': 'Результаты оптимизации (арбитраж)',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderOptimizerError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('traceback', models.TextField(blank=True, default='', verbose_name='Трассировка ошибки')),
                ('type', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип ошибки')),
                ('optimizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage_traders.arbitragetraderoptimizer', verbose_name='Оптимизатор')),
            ],
            options={
                'verbose_name': 'Ошибка оптимизатора (арбитраж)',
                'verbose_name_plural': 'Ошибки оптимизатора (арбитраж)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Тип позиции')),
                ('left_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Тип позиции (первая биржа)')),
                ('right_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Тип позиции (вторая биржа)')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10, verbose_name='Статус позиции')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Количество актива')),
                ('left_open_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена открытия (первая биржа)')),
                ('left_close_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена закрытия (первая биржа)')),
                ('right_open_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена открытия (вторая биржа)')),
                ('right_close_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Цена закрытия (вторая биржа)')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('close_reason', models.CharField(blank=True, choices=[('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('opposite_signal', 'Opposite Signal'), ('strategy', 'Strategy'), ('timeout', 'Timeout'), ('manual', 'Manual')], default='', max_length=20, verbose_name='Причина закрытия')),
                ('left_total_fee', models.DecimalField(decimal_places=18, default=Decimal('0.00'), max_digits=30, verbose_name='Комиссия (первая биржа)')),
                ('right_total_fee', models.DecimalField(decimal_places=18, default=Decimal('0.00'), max_digits=30, verbose_name='Комиссия (вторая биржа)')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='arbitrage_traders.arbitragetrader', verbose_name='Арбитражный трейдер')),
            ],
            options={
                'verbose_name': 'Арбитражная позиция трейдера',
                'verbose_name_plural': 'Арбитражные позиции трейдера',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('left_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_left_orders', to='exchange_clients.exchangeclientorder', verbose_name='Первый ордер')),
                ('right_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_right_orders', to='exchange_clients.exchangeclientorder', verbose_name='Второй ордер')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='arbitrage_traders.arbitragetrader', verbose_name='Арбитражный трейдер')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='arbitrage_traders.arbitragetraderposition', verbose_name='Позиция трейдера')),
            ],
            options={
                'verbose_name': 'Ордер арбитражного трейдера',
                'verbose_name_plural': 'Ордера арбитражного трейдера',
            },
        ),
        migrations.CreateModel(
            name='ArbitrageTraderSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время сигнала')),
                ('left_price', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена (первая биржа)')),
                ('right_price', models.DecimalField(decimal_places=18, max_digits=30, verbose_name='Цена (вторая биржа)')),
                ('left_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('wait', 'Wait')], max_length=10, verbose_name='Тип (первая биржа)')),
                ('right_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('wait', 'Wait')], max_length=10, verbose_name='Тип (вторая биржа)')),
                ('data', models.JSONField()),
                ('left_candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_left_signals', to='exchanges.exchangecandle', verbose_name='Первая свеча')),
                ('right_candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_right_signals', to='exchanges.exchangecandle', verbose_name='Вторая свеча')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='arbitrage_traders.arbitragetrader', verbose_name='Арбитражный трейдер')),
            ],
            options={
                'verbose_name': 'Арбитражный сигнал трейдера',
                'verbose_name_plural': 'Арбитражные сигналы трейдера',
            },
        ),
        migrations.AddConstraint(
            model_name='arbitragetrader',
            constraint=models.UniqueConstraint(fields=('left_candle_source', 'right_candle_source', 'left_exchange_client', 'right_exchange_client', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy'), name='unique_arbitrage_trader'),
        ),
        migrations.AddConstraint(
            model_name='arbitragetraderoptimizer',
            constraint=models.UniqueConstraint(fields=('algorithm', 'left_candle_source', 'right_candle_source', 'strategy_class_name', 'risk_manager_class_name', 'initial_balance', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy', 'roi_weight', 'r2_weight', 'sharpe_weight', 'win_rate_weight'), name='unique_arbitrage_trader_optimizer'),
        ),
        migrations.AddConstraint(
            model_name='arbitragetraderposition',
            constraint=models.UniqueConstraint(fields=('trader', 'opened_at', 'type', 'amount'), name='unique_arbitrage_position'),
        ),
        migrations.AddConstraint(
            model_name='arbitragetraderorder',
            constraint=models.UniqueConstraint(fields=('trader', 'left_order', 'right_order', 'position'), name='unique_arbitrage_trader_order'),
        ),
        migrations.AddConstraint(
            model_name='arbitragetradersignal',
            constraint=models.UniqueConstraint(fields=('trader', 'timestamp', 'left_type', 'right_type'), name='unique_arb_trader_signal'),
        ),
    ]
