# Generated by Django 5.2.6 on 2026-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0001_initial'),
        ('candle_sources', '0001_initial'),
        ('exchange_clients', '0002_alter_exchangeclientbalance_exchange_client_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='arbitragetrader',
            constraint=models.UniqueConstraint(fields=('left_candle_source', 'right_candle_source', 'left_exchange_client', 'right_exchange_client', 'strategy', 'risk_manager', 'initial_balance', 'max_drawdown_pct', 'max_positions_count', 'close_position_by_opposite_signal', 'close_position_by_strategy'), name='unique_arbitrage_trader'),
        ),
    ]
