# Generated by Django 5.2.6 on 2026-02-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbitrageoptimizationalgorithm',
            options={'verbose_name': 'Арбитражный алгоритм оптимизации', 'verbose_name_plural': 'Арбитражные алгоритмы оптимизации'},
        ),
        migrations.AlterModelOptions(
            name='arbitragetradererror',
            options={'ordering': ['-created_at'], 'verbose_name': 'Арбитражная ошибка трейдера', 'verbose_name_plural': 'Арбитражные ошибки трейдера'},
        ),
        migrations.AlterModelOptions(
            name='arbitragetraderoptimizer',
            options={'verbose_name': 'Арбитражный оптимизатор трейдера', 'verbose_name_plural': 'Арбитражные оптимизаторы трейдеров'},
        ),
        migrations.AlterModelOptions(
            name='arbitragetraderposition',
            options={'verbose_name': 'Арбитражная позиция трейдера', 'verbose_name_plural': 'Арбитражные позиции трейдера'},
        ),
        migrations.AlterModelOptions(
            name='arbitragetradersignal',
            options={'verbose_name': 'Арбитражный сигнал трейдера', 'verbose_name_plural': 'Арбитражные сигналы трейдера'},
        ),
        migrations.AlterField(
            model_name='arbitragetradererror',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='arbitrage_traders.arbitragetrader', verbose_name='Арбитражный трейдер'),
        ),
        migrations.AlterField(
            model_name='arbitragetraderorder',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='arbitrage_traders.arbitragetrader', verbose_name='Арбитражный трейдер'),
        ),
        migrations.AlterField(
            model_name='arbitragetraderposition',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='arbitrage_traders.arbitragetrader', verbose_name='Арбитражный трейдер'),
        ),
        migrations.AlterField(
            model_name='arbitragetradersignal',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='arbitrage_traders.arbitragetrader', verbose_name='Арбитражный трейдер'),
        ),
    ]
