# Generated by Django 5.2.6 on 2026-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0002_arbitragetrader_candles_lookback_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetradererror',
            name='traceback',
            field=models.TextField(blank=True, default='', verbose_name='Traceback'),
        ),
        migrations.AlterField(
            model_name='arbitragetraderoptimizererror',
            name='traceback',
            field=models.TextField(blank=True, default='', verbose_name='Traceback'),
        ),
    ]
