# Generated by Django 5.2.6 on 2026-02-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0002_alter_arbitrageoptimizationalgorithm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetraderorder',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='arbitrage_traders.arbitragetraderposition', verbose_name='Позиция трейдера'),
        ),
    ]
