# Generated by Django 5.2.6 on 2026-03-26 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0003_alter_arbitragetradererror_traceback_and_more'),
        ('exchange_clients', '0005_alter_exchangeclientorder_exchange_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetraderorder',
            name='left_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_trader_left_order', to='exchange_clients.exchangeclientorder', verbose_name='Первый ордер'),
        ),
        migrations.AlterField(
            model_name='arbitragetraderorder',
            name='right_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_trader_right_order', to='exchange_clients.exchangeclientorder', verbose_name='Второй ордер'),
        ),
    ]
