# Generated by Django 5.2.6 on 2026-02-14 19:49

from decimal import Decimal
from django.db import migrations, models


def migrate_total_fee_forward(apps, schema_editor):
    """Переносит данные из total_fee в left_total_fee и right_total_fee."""
    ArbitrageTraderPosition = apps.get_model(
        "arbitrage_traders", "ArbitrageTraderPosition"
    )
    ArbitrageTraderPosition.objects.all().update(
        left_total_fee=models.F("total_fee") / 2,
        right_total_fee=models.F("total_fee") / 2,
    )


def migrate_total_fee_backward(apps, schema_editor):
    """Восстанавливает total_fee из left_total_fee + right_total_fee."""
    ArbitrageTraderPosition = apps.get_model(
        "arbitrage_traders", "ArbitrageTraderPosition"
    )
    ArbitrageTraderPosition.objects.all().update(
        total_fee=models.F("left_total_fee") + models.F("right_total_fee"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0003_alter_arbitragetraderorder_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='left_total_fee',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.00'), max_digits=30, verbose_name='Комиссия (первая биржа)'),
        ),
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='right_total_fee',
            field=models.DecimalField(decimal_places=18, default=Decimal('0.00'), max_digits=30, verbose_name='Комиссия (вторая биржа)'),
        ),
        migrations.RunPython(
            migrate_total_fee_forward,
            migrate_total_fee_backward,
        ),
        migrations.RemoveField(
            model_name='arbitragetraderposition',
            name='total_fee',
        ),
    ]
