# Generated by Django 5.2.6 on 2026-03-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0004_alter_arbitragetraderorder_left_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='arbitragetraderposition',
            name='unique_arbitrage_position',
        ),
        migrations.RemoveField(
            model_name='arbitragetraderposition',
            name='type',
        ),
        migrations.AddConstraint(
            model_name='arbitragetraderposition',
            constraint=models.UniqueConstraint(fields=('trader', 'opened_at', 'amount', 'left_type', 'right_type'), name='unique_arbitrage_position'),
        ),
    ]
