# Generated by Django 5.2.6 on 2026-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0007_alter_arbitragetraderoptimizer_lookback_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetrader',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('rebooting', 'Rebooting'), ('clearing', 'Clearing'), ('error', 'Error'), ('paused', 'Paused')], default='disabled', verbose_name='Статус'),
        ),
    ]
