# Generated by Django 5.2.6 on 2026-04-08 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0008_alter_arbitragetrader_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetraderoptimizererror',
            name='optimizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='arbitrage_traders.arbitragetraderoptimizer', verbose_name='Оптимизатор'),
        ),
    ]
