# Generated by Django 5.2.6 on 2026-04-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0009_alter_arbitragetraderoptimizererror_optimizer'),
        ('candle_sources', '0012_remove_candlesource_is_active_candlesource_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetrader',
            name='left_candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_left_traders', to='candle_sources.candlesource', verbose_name='Первый источник свечей'),
        ),
        migrations.AlterField(
            model_name='arbitragetrader',
            name='right_candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_right_traders', to='candle_sources.candlesource', verbose_name='Второй источник свечей'),
        ),
        migrations.AlterField(
            model_name='arbitragetraderoptimizer',
            name='left_candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_optimizer_left', to='candle_sources.candlesource', verbose_name='Первый источник свечей'),
        ),
        migrations.AlterField(
            model_name='arbitragetraderoptimizer',
            name='right_candle_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_optimizer_right', to='candle_sources.candlesource', verbose_name='Второй источник свечей'),
        ),
    ]
