# Generated by Django 5.2.6 on 2026-04-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0010_alter_arbitragetrader_left_candle_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='left_close_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Кол-во закрытия (первая биржа)'),
        ),
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='left_open_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Кол-во открытия (первая биржа)'),
        ),
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='right_close_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Кол-во закрытия (вторая биржа)'),
        ),
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='right_open_amount',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Кол-во открытия (вторая биржа)'),
        ),
    ]
