# Generated by Django 5.2.6 on 2026-04-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0011_arbitragetraderposition_left_close_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='left_close_cost',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Стоимость закрытия (первая биржа)'),
        ),
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='left_open_cost',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Стоимость открытия (первая биржа)'),
        ),
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='right_close_cost',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Стоимость закрытия (вторая биржа)'),
        ),
        migrations.AddField(
            model_name='arbitragetraderposition',
            name='right_open_cost',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='Стоимость открытия (вторая биржа)'),
        ),
    ]
