# Generated by Django 5.2.6 on 2026-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0012_arbitragetraderposition_left_close_cost_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='arbitragetraderposition',
            name='unique_arbitrage_position',
        ),
        migrations.RemoveField(
            model_name='arbitragetraderposition',
            name='amount',
        ),
        migrations.AddConstraint(
            model_name='arbitragetraderposition',
            constraint=models.UniqueConstraint(fields=('trader', 'opened_at', 'left_type', 'right_type'), name='unique_arbitrage_position'),
        ),
    ]
