# Generated by Django 5.2.6 on 2026-04-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_traders', '0013_remove_arbitragetraderposition_unique_arbitrage_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragetrader',
            name='candles_lookback_count',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (10, '10'), (50, '50'), (100, '100'), (200, '200'), (500, '500'), (1000, '1000'), (2000, '2000'), (5000, '5000'), (10000, '10000')], default=10, verbose_name='Макс. количество свечей'),
        ),
    ]
