# Generated by Django 5.2.1 on 2025-06-06 16:03

import strategies.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(choices=strategies.domain.base.StrategyRegistry.get_choices, default='RenkoStrategy', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arguments', models.JSONField()),
            ],
        ),
    ]
