# Generated by Django 5.2.6 on 2026-02-08 21:42

import strategies.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название арбитражной стратегии')),
                ('class_name', models.CharField(choices=strategies.domain.base.ArbitrageStrategyRegistry.get_choices, max_length=100, verbose_name='Класс арбитражной стратегии')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)')),
            ],
            options={
                'verbose_name': 'Арбитражная стратегия',
                'verbose_name_plural': 'Арбитражные стратегии',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название стратегии')),
                ('class_name', models.CharField(choices=strategies.domain.base.StrategyRegistry.get_choices, max_length=100, verbose_name='Класс стратегии')),
                ('arguments', models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)')),
            ],
            options={
                'verbose_name': 'Стратегия',
                'verbose_name_plural': 'Стратегии',
            },
        ),
    ]
