# Generated by Django 5.2.1 on 2025-06-30 22:54

import strategies.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='arguments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры (аргументы)'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='class_name',
            field=models.CharField(choices=strategies.domain.base.StrategyRegistry.get_choices, max_length=100, verbose_name='Класс стратегии'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название стратегии'),
        ),
    ]
