# Generated by Django 5.2.6 on 2026-02-08 13:55

import strategies.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragestrategy',
            name='class_name',
            field=models.CharField(choices=strategies.domain.base.ArbitrageStrategyRegistry.get_choices, max_length=100, verbose_name='Класс арбитражной стратегии'),
        ),
    ]
