# Generated by Django 5.2.1 on 2025-06-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Стратегия', 'verbose_name_plural': 'Стратегии'},
        ),
    ]
