# Generated by Django 5.2.1 on 2025-06-06 19:32

import strategies.domain.strategies.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_alter_strategy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='class_name',
            field=models.CharField(choices=strategies.domain.strategies.base.StrategyRegistry.get_choices, max_length=100),
        ),
    ]
