# Generated by Django 5.2.6 on 2026-02-05 21:11

import strategies.domain.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_arbitragestrategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragestrategy',
            name='class_name',
            field=models.CharField(choices=strategies.domain.base.StrategyRegistry.get_choices, max_length=100, verbose_name='Класс стратегии'),
        ),
        migrations.AlterField(
            model_name='arbitragestrategy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='arbitragestrategy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='arbitragestrategy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
