# Generated by Django 5.2.1 on 2025-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_alter_strategy_created_at_alter_strategy_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
