# Generated by Django 5.2.6 on 2025-11-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_alter_strategy_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название стратегии'),
        ),
    ]
