# Generated by Django 5.1.3 on 2025-06-04 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1m', max_length=3)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.tradingpair')),
            ],
        ),
    ]
