# Generated by Django 5.2.6 on 2026-02-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('token', models.CharField(max_length=512, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Telegram бот',
                'verbose_name_plural': 'Telegram боты',
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID чата')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bots.telegrambot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Telegram чат',
                'verbose_name_plural': 'Telegram чаты',
            },
        ),
    ]
