# Generated by Django 5.2.6 on 2026-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='token',
            field=models.CharField(max_length=512, unique=True, verbose_name='Токен'),
        ),
        migrations.AddConstraint(
            model_name='telegramchat',
            constraint=models.UniqueConstraint(fields=('bot', 'chat_id'), name='unique_telegram_chat'),
        ),
    ]
