# Generated by Django 5.2.6 on 2025-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0002_telegramchat_is_active_alter_telegrambot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
